### ISSUE TITLE
Error calculating Source Area

### ISSUE THREAD

**Issue by kitbenjamin** [UMEP-dev/UMEP#174]
When following the [tutorial](https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/Footprint.html):

I have set up the source area model as in the screenshot 
![Source_area_window](https://user-images.githubusercontent.com/53219529/86244898-90feca80-bba0-11ea-99af-269a3f940143.png)

leads to following error:

```
2020-07-01T13:34:45     WARNING    Traceback (most recent call last):
              File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP-SuPy-QGIS3\FootprintModel\footprint_model.py", line 551, in start_process
              maxfetch=r,rm=Rm)
              File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP-SuPy-QGIS3\FootprintModel\KingsFootprint_UMEP.py", line 169, in footprintiterKAM
              rotatedphi = scnd.rotate(full, rotang, order =0, reshape=False, mode='nearest')
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\scipy\ndimage\interpolation.py", line 718, in rotate
              out_center = rot_matrix @ ((out_plane_shape - 1) / 2)
             ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)
```

I get the same when using London dataset

**Comment by biglimp** [comment]
Fixed in upcoming version 3.14.2
