### ISSUE TITLE
Python error in QGIS during launching SEBE algorithm

### ISSUE THREAD

**Issue by adamsss92** [UMEP-dev/UMEP#182]
Hello,

I'm receiving the following python error in QGIS (3.6 and 3.12 version) during i try to launch SEBE algorithm:

`2020-08-17T16:16:39     WARNING    Traceback (most recent call last):
              File "C:/Users/fotoraporty1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SEBE\sebe.py", line 444, in start_progress
              Solweig_2015a_metdata_noload(self.metdata,location, UTC)
              File "C:/Users/fotoraporty1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\Utilities\SEBESOLWEIGCommonFiles\Solweig_v2015_metdata_noload.py", line 21, in Solweig_2015a_metdata_noload
              data_len = len(met[:, 0])
             TypeError: 'NoneType' object is not subscriptable`

I will just add that other functions worked normally.

Best regards

**Comment by biglimp** [comment]
Based on the error message it seems that there is something wrong with your meteorological data. Is it UMEP formatted (i.e. 24 columns).

**Comment by biglimp** [comment]
Any new updates on this bug report? Was this issue resolved?

**Comment by biglimp** [comment]
I will close this issue now as no response was came in.
