### ISSUE TITLE
Error with input data for SUEWS

### ISSUE THREAD

**Issue by kaywhytee** [UMEP-dev/UMEP#185]
Hi, I prepared existing meteorological data with UMEP's MetData pre-processor and tried it with spatial data calculated for a point (in SUEWS simple) or a grid (in SUEWS advanced). However, the model cannot run due to errors in the forcing data. Original issue in ZERO wind speeds has already been corrected but the problem persists.

Help is much appreciated!

Here are screenshots of the pop-up error messages.
<img width="361" alt="error_suewssimple" src="https://user-images.githubusercontent.com/70948065/92464625-fc4bc500-f1ff-11ea-86af-c9d5d88dd1cb.png">
<img width="362" alt="error_suewsadvanced" src="https://user-images.githubusercontent.com/70948065/92464648-040b6980-f200-11ea-979d-03896f664b18.png">

Here are the files (from SUEWS prepare) and settings used for the model run.
![hk_suewsimple_settings](https://user-images.githubusercontent.com/70948065/92464692-17b6d000-f200-11ea-93aa-ad3d7604d3c9.png)
[HK_KP_metdata_2018_format3.txt](https://github.com/UMEP-dev/UMEP/files/5187666/HK_KP_metdata_2018_format3.txt)
[MK_suews_prepare2.zip](https://github.com/UMEP-dev/UMEP/files/5187673/MK_suews_prepare2.zip)

**Comment by sunt05** [comment]
> <img alt="error_suewsadvanced" width="362" src="https://user-images.githubusercontent.com/70948065/92464648-040b6980-f200-11ea-979d-03896f664b18.png">
> 

Can you please post the info of the `SuPy.log` file indicated above?

**Comment by kaywhytee** [comment]
Here's all the info on SuPy.log. However, according to the timestamps, they do not correspond to the above runs which failed. For example, at 14:27, I tried the tutorial for SUEWS advanced with data from NYC.
```python
2020-09-08 13:22:06,822 - SuPy - INFO - All cache cleared.
2020-09-08 13:22:10,582 - SuPy - INFO - All cache cleared.
2020-09-08 13:22:14,951 - SuPy - INFO - SuPy is validating `df_forcing`...
2020-09-08 13:22:27,234 - SuPy - ERROR - Issues found in `df_forcing`:
`u` should be between [0.0001, 60] but `0.0` is found at 2018-01-08 17:00:00
2020-09-08 13:22:27,234 - SuPy - CRITICAL - `df_forcing` is NOT valid to drive SuPy!
2020-09-08 14:25:41,066 - SuPy - INFO - All cache cleared.
2020-09-08 14:25:43,400 - SuPy - ERROR - /Users/kwokyuting/Documents/work/ESSC4260_EASC5260_TA/UMEP_tutorial_test/HKdata/MK_suews_prepare/initialconditionsnyc_2018.nml does not exists!
Traceback (most recent call last):
  File "/Users/kwokyuting/Library/Python/3.7/lib/python/site-packages/supy/_load.py", line 232, in load_SUEWS_nml
    df_res = pd.DataFrame(f90nml.read(str_file))
  File "/Users/kwokyuting/Library/Python/3.7/lib/python/site-packages/f90nml/__init__.py", line 31, in read
    return parser.read(nml_path)
  File "/Users/kwokyuting/Library/Python/3.7/lib/python/site-packages/f90nml/parser.py", line 262, in read
    nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kwokyuting/Documents/work/ESSC4260_EASC5260_TA/UMEP_tutorial_test/HKdata/MK_suews_prepare/initialconditionsnyc_2018.nml'
2020-09-08 14:27:33,748 - SuPy - INFO - All cache cleared.
2020-09-08 14:27:37,288 - SuPy - INFO - All cache cleared.
2020-09-08 14:27:41,280 - SuPy - INFO - SuPy is validating `df_forcing`...
2020-09-08 14:27:55,241 - SuPy - INFO - All checks for `df_forcing` passed!
2020-09-08 14:27:55,242 - SuPy - INFO - SuPy is validating `df_state`...
2020-09-08 14:27:56,382 - SuPy - INFO - All checks for `df_state` passed!
2020-09-08 14:27:56,383 - SuPy - INFO - ====================
2020-09-08 14:27:56,383 - SuPy - INFO - Simulation period:
2020-09-08 14:27:56,383 - SuPy - INFO -   Start: 2010-01-01 00:05:00
2020-09-08 14:27:56,383 - SuPy - INFO -   End: 2011-01-01 00:00:00
2020-09-08 14:27:56,383 - SuPy - INFO -
2020-09-08 14:27:56,384 - SuPy - INFO - No. of grids: 16
2020-09-08 14:27:56,384 - SuPy - INFO - SuPy is running in serial mode
2020-09-08 14:41:04,851 - SuPy - INFO - Execution time: 788.5 s
2020-09-08 14:41:04,879 - SuPy - INFO - ====================
```

**Comment by kaywhytee** [comment]
I just restarted QGIS and tried again. Here's the Python error message. Will this help to debug the issue?
Thanks a lot!

This is when I run SUEWS advanced.
```
Traceback (most recent call last):
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/Users/kwokyuting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 22, in classFactory
              bootstrap_with_ui(iface)
              File "/Users/kwokyuting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 31, in bootstrap_with_ui
              from gis4wrf.plugin.ui.helpers import WaitDialog
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/Users/kwokyuting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/helpers.py", line 17, in 
              from PyQt5.Qt import QWebPage
             ImportError: cannot import name 'QWebPage' from 'PyQt5.Qt' (/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/PyQt5/Qt.so)
             
2020-09-08T20:08:47     WARNING    Traceback (most recent call last):
              File "/Users/kwokyuting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/UMEP/SUEWS/suews.py", line 314, in start_progress
              suews_wrapper.wrapper(self.model_dir)
              File "/Users/kwokyuting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/UMEP/suewsmodel/suews_wrapper.py", line 57, in wrapper
              df_output, df_state_final = sp.run_supy(df_forcing, df_state_init, check_input=True, serial_mode=True)
              File "/Users/kwokyuting/Library/Python/3.7/lib/python/site-packages/supy/_supy_module.py", line 333, in run_supy
              "SuPy stopped entering simulation due to invalid initial states!"
             RuntimeError: SuPy stopped entering simulation due to invalid initial states!
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Users/kwokyuting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/UMEP/SUEWS/suews.py", line 353, in start_progress
              "Check: " + str(list(Path.cwd().glob('SuPy.log'))[0]) + "\r\n\r\n"
             IndexError: list index out of range
```

**Comment by kaywhytee** [comment]
For SUEWS simple, the error message is like this:
```
Traceback (most recent call last):
              File "/Users/kwokyuting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/UMEP/SuewsSimple/suews_simple.py", line 593, in start_progress
              suews_wrapper.wrapper(self.model_dir, year=YYYY)
              File "/Users/kwokyuting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/UMEP/suewsmodel/suews_wrapper.py", line 51, in wrapper
              df_forcing = sp.load_forcing_grid(path_runcontrol, grid).loc[f'{year}'] # new (loc) from 2020a
              File "/Users/kwokyuting/Library/Python/3.7/lib/python/site-packages/supy/_supy_module.py", line 205, in load_forcing_grid
              path_input, filecode, grid, tstep_met_in, multiplemetfiles
              File "/Users/kwokyuting/Library/Python/3.7/lib/python/site-packages/supy/_load.py", line 657, in load_SUEWS_Forcing_met_df_raw
              path_input, forcingfile_met_pattern
              File "/Users/kwokyuting/Library/Python/3.7/lib/python/site-packages/supy/_load.py", line 722, in load_SUEWS_Forcing_met_df_pattern
              df_forcing_met = set_index_dt(df_forcing_met)
              File "/Users/kwokyuting/Library/Python/3.7/lib/python/site-packages/supy/_load.py", line 636, in set_index_dt
              loc_issue = idx_dt[~dt_diff]
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/pandas/core/generic.py", line 1465, in __invert__
              arr = operator.inv(com.values_from_object(self))
             TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Users/kwokyuting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/UMEP/SuewsSimple/suews_simple.py", line 597, in start_progress
              "Check also: " + str(list(Path.cwd().glob('SuPy.log'))[0]) + "\r\n\r\n"
             IndexError: list index out of range
```

**Comment by sunt05** [comment]
> Here's all the info on SuPy.log. However, according to the timestamps, they do not correspond to the above runs which failed. For example, at 14:27, I tried the tutorial for SUEWS advanced with data from NYC.
> 
> ```python
> 2020-09-08 13:22:06,822 - SuPy - INFO - All cache cleared.
> 2020-09-08 13:22:10,582 - SuPy - INFO - All cache cleared.
> 2020-09-08 13:22:14,951 - SuPy - INFO - SuPy is validating `df_forcing`...
> 2020-09-08 13:22:27,234 - SuPy - ERROR - Issues found in `df_forcing`:
> `u` should be between [0.0001, 60] but `0.0` is found at 2018-01-08 17:00:00
> 2020-09-08 13:22:27,234 - SuPy - CRITICAL - `df_forcing` is NOT valid to drive SuPy!
> 2020-09-08 14:25:41,066 - SuPy - INFO - All cache cleared.
> 2020-09-08 14:25:43,400 - SuPy - ERROR - /Users/kwokyuting/Documents/work/ESSC4260_EASC5260_TA/UMEP_tutorial_test/HKdata/MK_suews_prepare/initialconditionsnyc_2018.nml does not exists!
> Traceback (most recent call last):
>   File "/Users/kwokyuting/Library/Python/3.7/lib/python/site-packages/supy/_load.py", line 232, in load_SUEWS_nml
>     df_res = pd.DataFrame(f90nml.read(str_file))
>   File "/Users/kwokyuting/Library/Python/3.7/lib/python/site-packages/f90nml/__init__.py", line 31, in read
>     return parser.read(nml_path)
>   File "/Users/kwokyuting/Library/Python/3.7/lib/python/site-packages/f90nml/parser.py", line 262, in read
>     nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/kwokyuting/Documents/work/ESSC4260_EASC5260_TA/UMEP_tutorial_test/HKdata/MK_suews_prepare/initialconditionsnyc_2018.nml'
> 2020-09-08 14:27:33,748 - SuPy - INFO - All cache cleared.
> 2020-09-08 14:27:37,288 - SuPy - INFO - All cache cleared.
> 2020-09-08 14:27:41,280 - SuPy - INFO - SuPy is validating `df_forcing`...
> 2020-09-08 14:27:55,241 - SuPy - INFO - All checks for `df_forcing` passed!
> 2020-09-08 14:27:55,242 - SuPy - INFO - SuPy is validating `df_state`...
> 2020-09-08 14:27:56,382 - SuPy - INFO - All checks for `df_state` passed!
> 2020-09-08 14:27:56,383 - SuPy - INFO - ====================
> 2020-09-08 14:27:56,383 - SuPy - INFO - Simulation period:
> 2020-09-08 14:27:56,383 - SuPy - INFO -   Start: 2010-01-01 00:05:00
> 2020-09-08 14:27:56,383 - SuPy - INFO -   End: 2011-01-01 00:00:00
> 2020-09-08 14:27:56,383 - SuPy - INFO -
> 2020-09-08 14:27:56,384 - SuPy - INFO - No. of grids: 16
> 2020-09-08 14:27:56,384 - SuPy - INFO - SuPy is running in serial mode
> 2020-09-08 14:41:04,851 - SuPy - INFO - Execution time: 788.5 s
> 2020-09-08 14:41:04,879 - SuPy - INFO - ====================
> ```

based on the above info, you had a successful run for NYC following the tutorial, right?

**Comment by kaywhytee** [comment]
Yes, that's right. I have succeeded all the three SUEWS tutorials (basic, advanced, and spatial).

**Comment by sunt05** [comment]
After checking your input files, I found the following:
```
`startdls` should be between [1, 366] but `0.0` is found at 0 at index `1`
`enddls` should be between [1, 366] but `0.0` is found at 0 at index `1`
```
so `StartDLS` and `EndDLS` in `SUEWS_SiteSelect.txt` is not properly set.

**Comment by kaywhytee** [comment]
Thanks for looking into it. In Hong Kong, we do not have daylight-saving time, what should I put for the DLS period? Should I just input from day 1 to 1? or 365?

**Comment by sunt05** [comment]
see here: https://suews.readthedocs.io/en/latest/input_files/SUEWS_SiteInfo/SUEWS_SiteSelect.html#day-light-savings

**Comment by kaywhytee** [comment]
Got it, thank you for your kind help!
