### ISSUE TITLE
Python error: DSM Generator & OSM

### ISSUE THREAD

**Issue by CsillaVG** [UMEP-dev/UMEP#211]
Hej developers!

I receive a Python error whenever I try to generate DSM from Open Street Map. I am running QGIS 3.10.13 with UMEP 3.15.5 on a Windows 10 Edu machine. 

I've tried the DSM Generator with two projects and I've got following two Python warnings (see below).

Thank you for your help and for all your hard work!
Regards,

Csilla

1) WARNING    Traceback (most recent call last):
              File "C:/Users/cga/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\DSMGenerator\dsm_generator.py", line 497, in start_progress
              renameField(vlayer, 'building_l', 'bld_levels')
              File "C:/Users/cga/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\DSMGenerator\dsm_generator.py", line 494, in renameField
              ds.ExecuteSQL('ALTER TABLE {} RENAME COLUMN {} TO {}'.format(srcLayer.name(), oldFieldName, newFieldName))
             AttributeError: 'NoneType' object has no attribute 'ExecuteSQL'

2) WARNING    Traceback (most recent call last):
              File "C:/Users/cga/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\DSMGenerator\dsm_generator.py", line 433, in start_progress
              with urllib.request.urlopen(urlStr) as response:
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 222, in urlopen
              return opener.open(url, data, timeout)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 531, in open
              response = meth(req, response)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 641, in http_response
              'http', request, response, code, msg, hdrs)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 569, in error
              return self._call_chain(*args)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 503, in _call_chain
              result = func(*args)
              File "C:\OSGEO4~1\apps\Python37\lib\urllib\request.py", line 649, in http_error_default
              raise HTTPError(req.full_url, code, msg, hdrs, fp)
             urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by biglimp** [comment]
These are just warnings and should not cause an error. Please attach your DEM and state how you set your extent.

**Comment by CsillaVG** [comment]
Sure! The DEMs are attached, and I use them as extent (see screenshot).

![DSMgSetup](https://user-images.githubusercontent.com/53008258/103655390-74848600-4f67-11eb-93c5-857213be4999.PNG)

[Project_1.zip](https://github.com/UMEP-dev/UMEP/files/5770563/Project_1.zip)
[Project_2.zip](https://github.com/UMEP-dev/UMEP/files/5770564/Project_2.zip)

**Comment by CsillaVG** [comment]
Hi developers,

Please consider this issue resolved. Updating Python 3.7 within QGIS solved my problem.
Best,

Csilla
