### ISSUE TITLE
SUEWS module: save user input and output for diagnostics

### ISSUE THREAD

**Issue by sunt05** [UMEP-dev/UMEP#212]
often users might not manage to report issues with exact input for developers to reproduce the issues.
so, we need to properly save the user input and output for diagnostics.

**Comment by sunt05** [comment]
related #193

**Comment by biglimp** [comment]
I am trying to implement diagnostics but I am missing a Python library (tables). Is this not included when SuPy is installed? Can you please add that otherwise.

![image](https://user-images.githubusercontent.com/11908356/107968870-33908000-6faf-11eb-8ca3-a183eae5d6b6.png)

**Comment by biglimp** [comment]
Here is the actual Python error:

```
An error has occurred while executing Python code: 

ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables. 
Traceback (most recent call last):
  File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SuewsSimple\suews_simple.py", line 580, in start_progress
    suews_wrapper.wrapper(self.model_dir, self.iface, year=YYYY)
  File "C:/Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\suewsmodel\suews_wrapper.py", line 65, in wrapper
    df_forcing.to_hdf(fn_dump, key="df_forcing")
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\core\generic.py", line 2505, in to_hdf
    encoding=encoding,
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\io\pytables.py", line 280, in to_hdf
    path_or_buf, mode=mode, complevel=complevel, complib=complib
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\io\pytables.py", line 518, in __init__
    tables = import_optional_dependency("tables")
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\pandas\compat\_optional.py", line 92, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.
```

**Comment by biglimp** [comment]
Strange thing is that it says I have tables installed...

![image](https://user-images.githubusercontent.com/11908356/107969623-4a83a200-6fb0-11eb-8835-9e9c60985726.png)

**Comment by sunt05** [comment]
I now realise it might be challenging for ordinary users to get the `hdf5`-related packages properly installed using `pip`: as some pre-compiled packages cannot be properly delivered via the `pip` channel (`conda` does it thought) so let's revert this PR and I'll try to save the debugging info in another format at the supy side.

**Comment by biglimp** [comment]
I will keep it in but comment out. Then you can add changes when you solved it.
