### ISSUE TITLE
Pre-Processor, Download Data ERA-5, supy not installed/upgraded

### ISSUE THREAD

**Issue by jonas260492** [UMEP-dev/UMEP#243]
hi
I want to use UMEP SOLWEIG-tool and for this, I need the weather data. I wanted to use the pre-processor and download ERA-5 Data but it says:
*"This plugin requires the supy package to be installed OR upgraded. Please consult the FAQ in the manual for further information on how to install missing python packages."*
I installed and upgraded the supy package according to the handbook. Therefore I cannot explain what the problem is.

**Comment by biglimp** [comment]
What OS (Windows, Mac) are you using and what version of UMEP?

Open the Python Console in QGIS and type the following:
```
import supy as sp
sp.show_version() 
```
Report back the result.

**Comment by jonas260492** [comment]
Thanks!
I am using QGIS on windows. 
This is the error message when I call: import supy as sp:
*untimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 798, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\supy\__init__.py", line 17, in <module>
    from ._supy_module import (
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 798, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\supy\_supy_module.py", line 28, in <module>
    from ._check import check_forcing, check_state
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 798, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\supy\_check.py", line 11, in <module>
    from ._load import dict_var_type_forcing
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 798, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\supy\_load.py", line 8, in <module>
    from supy_driver import suews_driver as sd
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 798, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\jonas\AppData\Roaming\Python\Python37\site-packages\supy_driver\__init__.py", line 13, in <module>
    from supy_driver.suews_driver import (
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 798, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: numpy.core.multiarray failed to import*
I also tried to uninstall and install numpy again.

**Comment by jonas260492** [comment]
I just tried again and now it is working. Thank you very much!
