### ISSUE TITLE
processing_umep installation error

### ISSUE THREAD

**Issue by snu11** [UMEP-dev/UMEP#270]
I am getting following error when installing processing_umep

Windows 10 64bit

```
Couldn't load plugin 'processing_umep' due to an error when calling its classFactory() method 

ImportError: DLL load failed while importing _ufuncs: The specified module could not be found. 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS31~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\__init__.py", line 38, in classFactory
    from .processing_umep import ProcessingUMEPPlugin
  File "C:/PROGRA~1/QGIS31~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep.py", line 38, in 
    from .processing_umep_provider import ProcessingUMEPProvider
  File "C:/PROGRA~1/QGIS31~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep_provider.py", line 36, in 
    from .preprocessor.wall_heightaspect_algorithm import ProcessingWallHeightAscpetAlgorithm
  File "C:/PROGRA~1/QGIS31~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\preprocessor\wall_heightaspect_algorithm.py", line 52, in 
    from ..functions import wallalgorithms as wa
  File "C:/PROGRA~1/QGIS31~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\wallalgorithms.py", line 8, in 
    import scipy.ndimage.interpolation as sc
  File "C:/PROGRA~1/QGIS31~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS31~1.5\apps\Python39\lib\site-packages\scipy\ndimage\__init__.py", line 153, in 
    from .interpolation import *
  File "C:/PROGRA~1/QGIS31~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS31~1.5\apps\Python39\lib\site-packages\scipy\ndimage\interpolation.py", line 37, in 
    from scipy import special
  File "C:/PROGRA~1/QGIS31~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS31~1.5\apps\Python39\lib\site-packages\scipy\special\__init__.py", line 633, in 
    from . import _ufuncs
  File "C:/PROGRA~1/QGIS31~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed while importing _ufuncs: The specified module could not be found.


Python version: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] 
QGIS version: 3.16.5-Hannover Hannover, 58ba7c1e 
```

**Comment by biglimp** [comment]
It seems you have an issue with scipy for Python3. Make sure it is installed. See information here: https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#adding-missing-python-libraries-and-other-osgeo-functionalities

**Comment by biglimp** [comment]
I transfer this issue to the umep_processing repository. https://github.com/UMEP-dev/UMEP-processing
