### ISSUE TITLE
UMEP installation error 

### ISSUE THREAD

**Issue by phemiobe** [UMEP-dev/UMEP#355]
I have tried to install UMEP plugin several times ...all efforts is proving abortive. Even with the newest version 3.19.1. I have attached screenshot. I need help please as I have run out of ideas. I have also tried different versions of QGIS

![UMEP installation error](https://user-images.githubusercontent.com/97770101/151083884-72f72d67-db39-485a-a728-de4d7a28d1b2.PNG)

**Comment by phemiobe** [comment]
ModuleNotFoundError: No module named 'packaging' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\__init__.py", line 38, in classFactory
    from .processing_umep import ProcessingUMEPPlugin
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep.py", line 38, in 
    from .processing_umep_provider import ProcessingUMEPProvider
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep_provider.py", line 36, in 
    from .preprocessor.wall_heightaspect_algorithm import ProcessingWallHeightAscpetAlgorithm
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\preprocessor\wall_heightaspect_algorithm.py", line 56, in 
    from ..util.misc import saverasternd
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\__init__.py", line 5, in 
    from .supy_installer import setup_supy
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\supy_installer.py", line 4, in 
    from packaging import version
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'packaging'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.18.3-Zürich Zürich, 735cc85be9 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by biglimp** [comment]
This is because you have an older version of QGIS (3.16). You have two options:
1. Upgrade QGIS to at least 3.20 (3.22 is the latest one)
2. Install **packaging** via the OSGeo shell `pip install packaging` Following the instructions given at https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#adding-missing-python-libraries-and-other-osgeo-functionalities

**Comment by phemiobe** [comment]
Thank you so much. I got it resolved by downloading the latest version..
