### ISSUE TITLE
Unable to download UMEP from QGIS (Urgent)

### ISSUE THREAD

**Issue by Johnyan0000000** [UMEP-dev/UMEP#357]
**Describe the bug**
After i installed UMEP, it states that" Python error : Couldn't load plugin 'ale' due to an error when calling its classFactory() method See message log (Python Error) for more details."

the UMEP function could not function in my QGIS. Please help

**To Reproduce**
PYTHON error
2022-01-26T23:42:27     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/johny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ale\__init__.py", line 34, in classFactory
              from .advanced_line_editor import ALE
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/johny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ale\advanced_line_editor.py", line 30, in 
              from .tools import rmEdgeTool, rmVertexTool, closeGapTool2
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/johny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ale\tools\__init__.py", line 4, in 
              from .closeGapTool2 import closeGapTool2
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/johny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ale\tools\closeGapTool2.py", line 7, in 
              from ..addons import QgsPolylineV2
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/johny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ale\addons\QgsPolylineV2.py", line 2, in 
              import ogr
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'ogr'
Python warning
2022-01-26T23:42:28     WARNING    warning:C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py:793: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
              mod = _builtin_import(name, globals, locals, fromlist, level)
             
             traceback: File "", line 1, in 
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 354, in startPlugin
              if not _startPlugin(packageName):
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/johny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\__init__.py", line 34, in classFactory
              from .UMEP import UMEP
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "C:\Users/johny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\UMEP.py", line 32, in 
              from .SkyViewFactorCalculator.svf_calculator import SkyViewFactorCalculator
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "C:\Users/johny/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SkyViewFactorCalculator\svf_calculator.py", line 24, in 
              from future import standard_library
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1058, in _handle_fromlist
              File "", line 228, in _call_with_frames_removed
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "C:\PROGRA~1\QGIS31~1.16\apps\Python39\lib\site-packages\future\standard_library\__init__.py", line 65, in 
              import imp
              File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "C:\PROGRA~1\QGIS31~1.16\apps\Python39\lib\imp.py", line 31, in 
              warnings.warn("the imp module is deprecated in favour of importlib; "
             
             

**Desktop (please complete the following information):**
 - OS: [MSI windows ]
 - QGIS Version [e.g. 3.16.16]
 - UMEP Version [e.g. 3.19.1]
 - SuPy Version installed: 2021.11.2

**Screenshots**

**Data**
If applicable, add data files to help us reproduce your problem.

**Additional context**

**Comment by biglimp** [comment]
I would recommend to update QGIS. If that is not possible on your system, please let me know.

**Comment by Johnyan0000000** [comment]
Sorry, may I know how could I update the software? I download the update
file  from the website?

**Comment by biglimp** [comment]
Yes, that is one possibility. I also think you should have a setup shortcut in your start menu that you can use. Take a look at https://umep-docs.readthedocs.io/en/latest/Getting_Started.html

**Comment by biglimp** [comment]
@Johnyan0000000 , Is this issue still active or can I close this issue?

**Comment by biglimp** [comment]
As we did not get any reply, we assumed rhis was fixed.
