### ISSUE TITLE
ModuleNotFoundError: No module named 'xlrd' 

### ISSUE THREAD

**Issue by ML426** [UMEP-dev/UMEP#446]
Hi,
I have this errors mesage, how can i fix it, please?

`Impossible de charger l'extension 'UMEP' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'xlrd' 
Traceback (most recent call last):
  File "C:/Users/USER/.conda/envs/Qgis_envi/Library/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\__init__.py", line 34, in classFactory
    from .UMEP import UMEP
  File "C:/Users/USER/.conda/envs/Qgis_envi/Library/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\UMEP.py", line 54, in 
    from .SUEWSPrepare.suews_prepare import SUEWSPrepare
  File "C:/Users/USER/.conda/envs/Qgis_envi/Library/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare\suews_prepare.py", line 46, in 
    from .Modules.xlutils.copy import copy
  File "C:/Users/USER/.conda/envs/Qgis_envi/Library/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare\Modules\xlutils\copy.py", line 7, in 
    from xlutils.filter import process,XLRDReader,XLWTWriter
  File "C:/Users/USER/.conda/envs/Qgis_envi/Library/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare/Modules\xlutils\filter.py", line 10, in 
    import xlrd,xlwt
  File "C:/Users/USER/.conda/envs/Qgis_envi/Library/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'xlrd'

Version de Python : 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] 
Version de QGIS : 3.16.3-Hannover Hannover, exported `

**Comment by biglimp** [comment]
Two things. 1. I recommend you update your QGIS. THat might solve your issue directly. 2. See here how you can install missing python libraries (https://umep-docs.readthedocs.io/en/latest/Getting_Started.html)
