### ISSUE TITLE
ModuleNotFoundError: No module named 'xlrd' 

### ISSUE THREAD

**Issue by ML426** [UMEP-dev/UMEP#448]
Hi,
I have this message error. How can i fix it, please?

Impossible de charger l'extension 'UMEP-SuPy-QGIS3' provoque une erreur lors de l'appel à sa méthode classFactory() 

```
Traceback (most recent call last):
  File "C:/Users/USER/.conda/envs/Qgis_envi/Library/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP-SuPy-QGIS3\__init__.py", line 34, in classFactory
    from .UMEP import UMEP
  File "C:/Users/USER/.conda/envs/Qgis_envi/Library/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP-SuPy-QGIS3\UMEP.py", line 54, in 
    from .SUEWSPrepare.suews_prepare import SUEWSPrepare
  File "C:/Users/USER/.conda/envs/Qgis_envi/Library/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP-SuPy-QGIS3\SUEWSPrepare\suews_prepare.py", line 46, in 
    from .Modules.xlutils.copy import copy
  File "C:/Users/USER/.conda/envs/Qgis_envi/Library/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP-SuPy-QGIS3\SUEWSPrepare\Modules\xlutils\copy.py", line 7, in 
    from xlutils.filter import process,XLRDReader,XLWTWriter
  File "C:/Users/USER/.conda/envs/Qgis_envi/Library/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)

Version de Python : 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] 
Version de QGIS : 3.16.3-Hannover Hannover, exported 
```

**Comment by biglimp** [comment]
see Discussions #477, the one you just submitted.
