### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by willkochtitzky** [UMEP-dev/UMEP#469]
Hi, I got the below (and attached) error when I tried install the QGIS plugin on QGIS 3.16.16 on MacOS. Do you have any advice on how to fix this?

An error occurred during execution of following code:
import pyplugin_installer

Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/wkochtitzky/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/processing_umep/__init__.py", line 38, in classFactory
    from .processing_umep import ProcessingUMEPPlugin
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/wkochtitzky/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/processing_umep/processing_umep.py", line 38, in 
    from .processing_umep_provider import ProcessingUMEPProvider
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/wkochtitzky/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/processing_umep/processing_umep_provider.py", line 51, in 
    from .processor.solweig_algorithm import ProcessingSOLWEIGAlgorithm
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/wkochtitzky/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/processing_umep/processor/solweig_algorithm.py", line 70, in 
    from ..functions.SOLWEIGpython.CirclePlotBar import PolarBarPlot
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/wkochtitzky/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/processing_umep/functions/SOLWEIGpython/CirclePlotBar.py", line 3, in 
    from matplotlib.pyplot import figure, show
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/pyplot.py", line 36, in 
    import matplotlib.colorbar
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/colorbar.py", line 44, in 
    import matplotlib.contour as contour
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/contour.py", line 17, in 
    import matplotlib.text as text
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/text.py", line 16, in 
    from .textpath import TextPath  # Unused, but imported by others.
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/textpath.py", line 11, in 
    from matplotlib.mathtext import MathTextParser
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/mathtext.py", line 27, in 
    from PIL import Image
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/Image.py", line 94, in 
    from . import _imaging as core
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so, 0x0002): Library not loaded: /opt/X11/lib/libxcb.1.dylib
  Referenced from: /Applications/QGIS-LTR.app/Contents/Resources/python/site-packages/pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so
  Reason: tried: '/opt/X11/lib/libxcb.1.dylib' (no such file), '/usr/local/lib/libxcb.1.dylib' (no such file), '/usr/lib/libxcb.1.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 1, in 
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 354, in startPlugin
    if not _startPlugin(packageName):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 336, in _startPlugin
    _unloadPluginModules(packageName)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 466, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "", line 1174, in __iter__
  File "", line 1162, in _recalculate
  File "", line 1158, in _get_parent_path
KeyError: 'processing_umep'

Python version:
3.8.7 (default, Feb 10 2021, 09:04:08) 
[Clang 12.0.0 (clang-1200.0.32.29)]

QGIS version:
3.16.16-Hannover 'Hannover', f5778a89df

Python path:
['/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python', '/Users/wkochtitzky/Library/Application Support/QGIS/QGIS3/profiles/default/python', '/Users/wkochtitzky/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins', '/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python38.zip', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/lib-dynload', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg', '/Users/wkochtitzky/.local/lib/python3.8/site-packages', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8', '/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg', '/Users/wkochtitzky/Library/Application Support/QGIS/QGIS3/profiles/default/python', '/Users/wkochtitzky/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing', '/Users/wkochtitzky/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs']

<img width="1304" alt="Screen Shot 2022-10-29 at 6 08 38 PM" src="https://user-images.githubusercontent.com/30648918/198854164-37cdadb9-4944-496f-8437-fa5ce0e0cd5a.png">

**Comment by biglimp** [comment]
It looks like you have a low version of matplotlib but also old version of QGIS. I suggest you update QGIS and try again.

**Comment by willkochtitzky** [comment]
Thank you for your reply! I did update QGIS but that didnt fix it. I will look into updating Matplotlib, etc. Thanks, Will

**Comment by biglimp** [comment]
I am a windows user myself, so maybe some more experiences IOS user can help you here, e.g. @sunt05?

**Comment by sunt05** [comment]
This seems to be a X11 related issue - try [this one](https://www.xquartz.org) and see if it works.

**Comment by willkochtitzky** [comment]
Thanks @sunt05 for the advice! I got it working without problems on another Mac, but even after updating that XQuratz I am still getting errors on that original computer. I have a work around for the moment, thanks! I will try to dig into it more for that first machine. I really appreciate all the help!
