### ISSUE TITLE
SuPy Could not run with diagmethod error

### ISSUE THREAD

**Issue by phemiobe** [UMEP-dev/UMEP#510]
Hello, 
I tried to run SuPy but I encounter the following error. I don't know what actually this means

My SuPy version is 
Name: supy
Version: 2022.9.22
 

File "/home/people/20202815/.local/lib/python3.8/site-packages/supy/_run.py", line 117, in <dictcomp>
    dict_input = {k: dict_input[k] for k in list_var_input_multitsteps}
KeyError: 'diagmethod'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/people/20202815/.local/lib/python3.8/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/people/20202815/.local/lib/python3.8/site-packages/multiprocess/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/people/20202815/.local/lib/python3.8/site-packages/supy/_run.py", line 431, in run_save_supy
    df_output, df_state_final = run_supy_ser(
  File "/home/people/20202815/.local/lib/python3.8/site-packages/supy/_run.py", line 384, in run_supy_ser
    path_zip_debug = save_zip_debug(df_forcing, df_state_init)
  File "/home/people/20202815/.local/lib/python3.8/site-packages/supy/util/_debug.py", line 198, in save_zip_debug
    show_version(as_json=path_json_version.as_posix())
  File "/home/people/20202815/.local/lib/python3.8/site-packages/supy/_version.py", line 45, in show_version
    ser_json = pd.read_json(path_json, typ="series", convert_dates=False)
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 757, in read_json
    return json_reader.read()
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 915, in read
    obj = self._get_object_parser(self.data)
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 942, in _get_object_parser
    obj = SeriesParser(json, **kwargs).parse()
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 1064, in parse
    self._parse_no_numpy()
  File "/home/people/20202815/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 1229, in _parse_no_numpy
    data = loads(self.json, precise_float=self.precise_float)
ValueError: Expected object or value

**Comment by phemiobe** [comment]
Kindly see attached file for debugging
[supy_debug-75cca244.zip](https://github.com/UMEP-dev/UMEP/files/11016820/supy_debug-75cca244.zip)

**Comment by phemiobe** [comment]
the model however runs well with  version:
Name: supy
Version: 2022.3.17

However, I have got no output with the biogenic emissions (Fc	 FcPhoto	 FcRespi	 FcMetab	 FcTraff	 FcBuild	 FcPoint) which is the goal of this simulation. kindly see the
[1_2018_SUEWS_60.txt](https://github.com/UMEP-dev/UMEP/files/11023680/1_2018_SUEWS_60.txt)
 attached output for a grid..


Thanks for helping out

**Comment by sunt05** [comment]
thanks for providing the error info - I haven't tested your input but guess that's due to incompatible `df_state` for the newer version (i.e. `2022.9.22`).

Please use `sp.check_state(df_state_init )` to identify and fix the issue.

BTW, `diagmethod` is a new option introduced in a recent version for diagnosing near surface meteorology: https://suews.readthedocs.io/en/latest/input_files/RunControl/scheme_options.html#cmdoption-arg-DiagMethod
