### ISSUE TITLE
Python modules missing and startup error

### ISSUE THREAD

**Issue by Krammwerk** [UMEP-dev/UMEP#515]
**Describe the bug**
Pythoin modules are missing when installing/upgrading to the latest UMEP for Processing version in QGIS

See error below after trying to install the missing python modules automatically. I've tried in three versions of QGIS 3.2 (Odense), 3.14 (Hannover) and 3.3 (Hertogenbosch) with same error messages in all three versions.

Traceback (most recent call last):
  File "C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\H2gisConnection.py", line 23, in 
    import jaydebeapi
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'jaydebeapi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\__init__.py", line 38, in classFactory
    from .processing_umep import ProcessingUMEPPlugin
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep.py", line 38, in 
    from .processing_umep_provider import ProcessingUMEPProvider
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep_provider.py", line 54, in 
    from .processor.urock_processing_algorithm import URockAlgorithm
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\urock_processing_algorithm.py", line 63, in 
    from ..functions.URock import MainCalculation
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\MainCalculation.py", line 11, in 
    from . import H2gisConnection
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\H2gisConnection.py", line 27, in 
    exit("'jaydebeapi' Python package is missing")
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 'jaydebeapi' Python package is missing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\pyplugin_installer\installer.py", line 344, in installPlugin
    if startPlugin(plugin["id"]):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 354, in startPlugin
    if not _startPlugin(packageName):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 336, in _startPlugin
    _unloadPluginModules(packageName)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 466, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "", line 1115, in __iter__
  File "", line 1103, in _recalculate
  File "", line 1099, in _get_parent_path
KeyError: 'processing_umep.functions'

Python version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS version:
3.16.1-Hannover 'Hannover', b381a90dca

Python path:
['C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\UMEP\\SUEWSPrepare/Modules', 'C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\UMEP\\SUEWSPrepare/Modules', 'C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\LAStools', 'C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python', 'C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\Scripts', 'C:\\Program Files\\QGIS 3.16\\bin\\python37.zip', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\DLLs', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib', 'C:\\Program Files\\QGIS 3.16\\bin', 'C:\\Users\\a1227374\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages\\Pythonwin', 'C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/a1227374/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\vrtbuilderplugin', 'C:\\Users\\a1227374\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\vrtbuilderplugin\\vrtbuilder']

**Comment by biglimp** [comment]
What UMEP for Processing version do you have? Hoover over UMEP in the Processing panel to see the version.

**Comment by biglimp** [comment]
This issue is solved in new version.
