### ISSUE TITLE
error when running SUEWS advanced in UMEP

### ISSUE THREAD

**Issue by ozyaz** [UMEP-dev/UMEP#527]
hi all,

I came across this error log in SUEWS advanced.. 

```

QGIS-Version: 3.22.5-Białowieża 

QGIS-Codeversion: c2723178 

Qt-Version: 5.15.2 

Python-Version: 3.9.5 

GDAL-Version: 3.4.1 

GEOS-Version: 3.10.2-CAPI-1.16.0 

PROJ-Version: Rel. 8.2.1, January 1st, 2022 

PDAL-Version: 2.3.0 (git-version: 9f35b7) 

Algorithmus beginnt bei: 2023-06-05T17:09:56 

Algorithmus Urban Energy Balance: SUEWS v2020a startet… 

Eingabeparameter: 

{ 'AERO' : 0, 'ANTHRO' : 2, 'INPUT_DIR' : 'C:\\Users\\f6-cip29-t-ozya\\Desktop\\ÖY\\ROTH\\ROTH_Output_Suews_prep', 'NET' : 3, 'OHM' : 1, 'OUTPUT_DIR' : 'C:\\Users\\f6-cip29-t-ozya\\Desktop\\ÖY\\ROTH\\5-Output_SUEWS_advanced_ROTH\\ROTH_new_Jan-March', 'SMD' : 0, 'SNOW' : False, 'STAB' : 1, 'STORAGE' : 0, 'TIMERESOUT' : 60, 'WU' : 0, 'Z0' : 1 } 

 
 

SuPy version: 2023.5.26.dev0 

C:\Users\f6-cip29-t-ozya\AppData\Roaming\Python\Python39\site-packages\supy 

C:\Users\f6-cip29-t-ozya\AppData\Roaming\Python\Python39\site-packages\supy 

Creating RunControl.nml 

Initiating model 

Traceback (most recent call last): 
File "C:\Users/f6-cip29-t-ozya/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\suews_algorithm.py", line 241, in processAlgorithm 
df_state_init = sp.init_supy(path_runcontrol) 
File "C:\Users\f6-cip29-t-ozya\AppData\Roaming\Python\Python39\site-packages\supy\_supy_module.py", line 103, in init_supy 
df_state_init = load_InitialCond_grid_df( 
File "C:\Users\f6-cip29-t-ozya\AppData\Roaming\Python\Python39\site-packages\supy\_load.py", line 1835, in load_InitialCond_grid_df 
df_init = add_file_gridlayout_df(df_init) 
File "C:\Users\f6-cip29-t-ozya\AppData\Roaming\Python\Python39\site-packages\supy\_load.py", line 1589, in add_file_gridlayout_df 
df_grid_layout.columns.set_names(df_init.columns.names, inplace=True) 
File "C:\Users\f6-cip29-t-ozya\AppData\Roaming\Python\Python39\site-packages\pandas\util\_decorators.py", line 311, in wrapper 
return func(*args, **kwargs) 
File "C:\Users\f6-cip29-t-ozya\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexes\base.py", line 1848, in set_names 
idx._set_names(names, level=level) 
File "C:\Users\f6-cip29-t-ozya\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexes\base.py", line 1731, in _set_names 
raise ValueError(f"Length of new names must be 1, got {len(values)}") 
ValueError: Length of new names must be 1, got 2 
 

Execution failed after 1.10 Sekunden 
```

**Comment by sunt05** [comment]
Please provide more details to help us reproduce your error:
- RunControl.nml 
- other input files

Please zip them and post the archive here.
Thanks!

**Comment by biglimp** [comment]
@ozyaz , is this issue still valid? Can we close?

**Comment by biglimp** [comment]
No response. I will close. Submit new or re-open if error not solved.
