### ISSUE TITLE
URock Java Exception

### ISSUE THREAD

**Issue by wangxiajun68** [UMEP-dev/UMEP#533]
Hello, UMEP development team, I get an error when running URock，The following is the operating environment and operation log

Desktop
 - OS: Windows11
 - QGIS Version  3.32
 - UMEP Version 4.0.2
 - SuPy Version 2023.5.26.dev0

Initiating algorithm
Creates an H2GIS Instance and load data
Traceback (most recent call last):
File "JdbcPreparedStatement.java", line 237, in org.h2.jdbc.JdbcPreparedStatement.execute
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "G:\QGIS\apps\Python39\lib\site-packages\jaydebeapi\__init__.py", line 534, in execute
is_rs = self._prep.execute()
org.h2.jdbc.org.h2.jdbc.JdbcSQLSyntaxErrorException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Function "NONE" not found; SQL statement:

CALL None('D:\DATA\UMEP\MRT\TEST\build_urock.gpkg','TEMPO');
CREATE TABLE build_pre_srid_20230630163143
AS SELECT *
FROM TEMPO;
[90022-200]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users/48943/AppData/Roaming/QGIS/QGIS3\profiles\1/python/plugins\urock_processing-main\urock_processing_algorithm.py", line 412, in processAlgorithm
MainCalculation.main(javaEnvironmentPath = javaEnvVar,
File "C:\Users/48943/AppData/Roaming/QGIS/QGIS3\profiles\1/python/plugins\urock_processing-main\MainCalculation.py", line 124, in main
loadData.loadData(fromCad = False,
File "C:\Users/48943/AppData/Roaming/QGIS/QGIS3\profiles\1/python/plugins\urock_processing-main\loadData.py", line 120, in loadData
loadFile(cursor = cursor,
File "C:\Users/48943/AppData/Roaming/QGIS/QGIS3\profiles\1/python/plugins\urock_processing-main\loadData.py", line 318, in loadFile
cursor.execute("""
File "G:\QGIS\apps\Python39\lib\site-packages\jaydebeapi\__init__.py", line 536, in execute
_handle_sql_exception()
File "G:\QGIS\apps\Python39\lib\site-packages\jaydebeapi\__init__.py", line 165, in _handle_sql_exception_jpype
reraise(exc_type, exc_info[1], exc_info[2])
File "G:\QGIS\apps\Python39\lib\site-packages\jaydebeapi\__init__.py", line 57, in reraise
raise value.with_traceback(tb)
File "G:\QGIS\apps\Python39\lib\site-packages\jaydebeapi\__init__.py", line 534, in execute
is_rs = self._prep.execute()
jaydebeapi.DatabaseError: org.h2.jdbc.JdbcSQLSyntaxErrorException: Function "NONE" not found; SQL statement:

CALL None('D:\DATA\UMEP\MRT\TEST\build_urock.gpkg','TEMPO');
CREATE TABLE build_pre_srid_20230630163143
AS SELECT *
FROM TEMPO;
[90022-200]

Execution failed after 0.09 秒

**Comment by j3r3m1** [comment]
Hi,
Thank you for your issue.
Unfortunately, only shapefile and geojson are currently supported as URock input.

**Comment by wangxiajun68** [comment]
> Hi, Thank you for your issue. Unfortunately, only shapefile and geojson are currently supported as URock input.

Thank you for your answer, my input data is the geojson file generated in URock Prepare using Göteborg test dataset

**Comment by j3r3m1** [comment]
> D:\DATA\UMEP\MRT\TEST\build_urock.gpkg

It seems you are using a geopackage file instead ?

**Comment by wangxiajun68** [comment]
> 
I am using build_vector.gpkg and veg_vector.gpkg

**Comment by j3r3m1** [comment]
Yes can you export this data into a geojson or shapefile ?

**Comment by wangxiajun68** [comment]
> Yes can you export this data into a geojson or shapefile ?

Thank you very much for your answer. I exported the file as shp and re-run it to solve the problem. I have another question to ask you. What do the HWS, VWS, and WS in the output represent?

**Comment by j3r3m1** [comment]
This is a good question. Can you please close this issue if resolved and open a discussion [here](https://github.com/UMEP-dev/UMEP/discussions/new/choose) for your question ?

**Comment by wangxiajun68** [comment]
> This is a good question. Can you please close this issue if resolved and open a discussion [here](https://github.com/UMEP-dev/UMEP/discussions/new/choose) for your question ?

OK，thank you
