### ISSUE TITLE
Bug with numpy  version 1.24.4

### ISSUE THREAD

**Issue by amerville98** [UMEP-dev/UMEP#544]
**Describe the bug**
I didn't manage to run umep because of an error concerning numpy. The error disappears by manually modifying the numpy version. So I switched from version 1.24.4 (initially installed and causing problems) to 1.23.3.

**Desktop (please complete the following information):**
 - OS: windows 10
 - QGIS Version 3.32.2
 - UMEP Version 4.0.2

**Screenshots**
The error with the svf generator :

Traceback (most recent call last): 
File "C:\Users/alexandre.merville/AppData/Roaming/QGIS/QGIS3\profiles\alexM/python/plugins\processing_umep\preprocessor\skyviewfactor_algorithm.py", line 123, in processAlgorithm dsm = gdal_dsm.ReadAsArray().astype(float) 
File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\osgeo\gdal.py", line 3328, in ReadAsArray from osgeo import gdal_array File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import mod = _builtin_import(name, globals, locals, fromlist, level) 
File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\osgeo\gdal_array.py", line 13, in <module> from . import _gdal_array File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import mod = _builtin_import(name, globals, locals, fromlist, level) 
ImportError: numpy.core.multiarray failed to import  Execution failed after 0.28 secondes

**Comment by biglimp** [comment]
Thank you for this info. We make sure that we use a numpy version that coincides with the version shipped with the QGIS/OSGeo installation. Thus, the version you used was higher than in the OSGEO repository, hence the issue you experienced. As this was no issue related to our code I will move this over to our Discussions page so that other users can that part of this.
