### ISSUE TITLE
Error in URock Analyzer

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP#546]
I am getting an error when trying to make a profile plot following the instructions from the [URock tutorial](https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/IntroductionToURock.html#introtourock).

```
QGIS version: 3.30.3-'s-Hertogenbosch
QGIS code revision: 2411cec1
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.7.0
GEOS version: 3.11.2-CAPI-1.17.2
PROJ version: Rel. 9.2.0, March 1st, 2023
PDAL version: 2.5.3 (git-version: 7ec4e6)
Algorithm started at: 2023-09-07T16:02:24
Algorithm 'Urban Wind Field: URock AnalyZer' starting…
Input parameters:
{ 'ID_FIELD_LINES' : 'fid', 'ID_FIELD_POLYGONS' : '', 'INPUT_LINES' : 'C:/temp/URockTutorial/Annedal_EPSG3006/lineprofile.gpkg|layername=lineprofile', 'INPUT_POLYGONS' : None, 'INPUT_WIND_FILE' : 'C:\\temp\\URockTutorial\\urock_out\\urock_output.nc', 'IS_STREAM' : True, 'OUTPUT_DIRECTORY' : 'C:\\temp\\URockTutorial\\urock_out', 'SIMULATION_NAME' : '' }

Load NetCDF file in Python and save as csv file...
Load csv file into H2GIS Database...
Calculates vertical sectional plot (along lines)...
Traceback (most recent call last):
File "JdbcPreparedStatement.java", line 237, in org.h2.jdbc.JdbcPreparedStatement.execute
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 534, in execute
is_rs = self._prep.execute()
org.h2.jdbc.org.h2.jdbc.JdbcSQLSyntaxErrorException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Function "NONE" not found; SQL statement:

CALL None('C:/temp/URockTutorial/Annedal_EPSG3006/lineprofile.gpkg','TEMPO');
CREATE TABLE LINES_20230907160224
AS SELECT *
FROM TEMPO;
[90022-200]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\postprocessor\urock_analyser_algorithm.py", line 251, in processAlgorithm
plotSectionalViews(pluginDirectory = plugin_directory,
File "C:\Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\urock_analyser_functions.py", line 198, in plotSectionalViews
loadFile(cursor = cursor,
File "C:\Users/xlinfr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\loadData.py", line 318, in loadFile
cursor.execute("""
File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 536, in execute
_handle_sql_exception()
File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 165, in _handle_sql_exception_jpype
reraise(exc_type, exc_info[1], exc_info[2])
File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 57, in reraise
raise value.with_traceback(tb)
File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 534, in execute
is_rs = self._prep.execute()
jaydebeapi.DatabaseError: org.h2.jdbc.JdbcSQLSyntaxErrorException: Function "NONE" not found; SQL statement:

CALL None('C:/temp/URockTutorial/Annedal_EPSG3006/lineprofile.gpkg','TEMPO');
CREATE TABLE LINES_20230907160224
AS SELECT *
FROM TEMPO;
[90022-200]

Execution failed after 136.46 seconds (2 minutes 16 seconds)

Loading resulting layers
Algorithm 'Urban Wind Field: URock AnalyZer' finished
```

**Comment by j3r3m1** [comment]
Vector files should be .shp or .geojson. Is there a simple way to set this constraint on the input ?

**Comment by biglimp** [comment]
No error when using shape but no output was created? What should come out, a jpg?

![image](https://github.com/UMEP-dev/UMEP/assets/11908356/ba8cd848-fd0c-409f-9bab-4d7a804758b2)

**Comment by j3r3m1** [comment]
yes jpg in the figure folder you have selected

**Comment by biglimp** [comment]
No file created:
![image](https://github.com/UMEP-dev/UMEP/assets/11908356/26b9f6d1-2c58-4fca-b82f-985abafa6eda)
![image](https://github.com/UMEP-dev/UMEP/assets/11908356/f99bb04d-bdb0-491a-9b9d-6ae29bdb6507)

**Comment by j3r3m1** [comment]
aha that is a bug ! Can you share netcdf and line files ?

**Comment by biglimp** [comment]
Too big for GH. Check your email.

**Comment by biglimp** [comment]
In the meantime I try to see if I can find a way to just include shp and json as input...

**Comment by j3r3m1** [comment]
deal !

**Comment by biglimp** [comment]
I actually cant see any code to be used in the Processing framework that can allow for certain vector formats, only types of geometry (e.g. lines). My workaround suggestion is to convert to shape if any other format than shp or json is used.

**Comment by j3r3m1** [comment]
OK I think I have found the problem. URock analyze is made to work using lines defined using only two points, your has 3. The idea of using one row per "two points line" is to use the ID of each line as figure name when plotting.

Two solutions:
- I can explode into multiline and call the figures "Line 1 -1", "Line 1-2"
- I just log an error and the user has to explode his / her line into "two points lines", each one having a different ID. Then the figures are called "Line 1" and "Line 2"

What do you think ?

**Comment by biglimp** [comment]
Yes! Now it works. I suggest that you give an error and that the user must have lines with only two points. In QGIS language, points is called vertex (pl: vertices).

**Comment by j3r3m1** [comment]
Solved in https://github.com/UMEP-dev/UMEP-processing/commit/4353e226de90cd81b6237797c595f789810d6525
