### ISSUE TITLE
Unable to run shadow Generator

### ISSUE THREAD

**Issue by denzle83** [UMEP-dev/UMEP#555]
I've primarily been using QGIS 3.24 as its the only one that seems to run UMEP. I've recently re-tried to install QGIS 3.32 and even QGIS 3.28 but just keep getting the below errors. I have gone into OSGEO setup to trouble shoot but nothing seems to work. Is there anything i can do?

Any help would be greatly appreciated.

Traceback (most recent call last):
File "C:\Users/dansh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\shadow_generator_algorithm.py", line 231, in processAlgorithm
dsm = gdal_dsm.ReadAsArray().astype(float)
File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\osgeo\gdal.py", line 3330, in ReadAsArray
from osgeo import gdal_array
File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\osgeo\gdal_array.py", line 13, in <module>
from . import _gdal_array
File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: numpy.core.multiarray failed to import

**Comment by denzle83** [comment]
I appear to have fixed it. If others are having the same problem my solution was to remove the numpy files from the folder and reinstall UMEP or use pip once they have been removed.

**Comment by Inspire71** [comment]
@denzle83 I have the same problem and I don't understand well the process you have followed to solve it, could you explain it in more detail?
thanks

**Comment by Inspire71** [comment]
Versión de QGIS: 3.34.2-Prizren
Revisión del código de QGIS: 7d199797fc
Versión de Qt: 5.15.3
Python version: 3.9.5
Versión de GDAL: 3.8.2
Versión de GEOS: 3.12.1-CAPI-1.18.1
Versión de PROJ: Rel. 9.3.1, December 1st, 2023
PDAL version: 2.6.0 (git-version: 3fced5)
El algoritmo comenzó en: 2024-01-03T15:00:49
Algoritmo 'Urban Geometry: Wall Height and Aspect' comenzando…
Parámetros de entrada:
{ 'INPUT' : 'C:/Users/atorr/UMEP/Goteborg_SWEREF99_1200/DatosBase/DSM_KRbig.tif', 'INPUT_LIMIT' : 3, 'OUTPUT_HEIGHT' : 'TEMPORARY_OUTPUT' }

C:\Users\atorr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\processing_umep\preprocessor
C:\Users\atorr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\processing_umep
Traceback (most recent call last):
File "C:\Users/atorr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\preprocessor\wall_heightaspect_algorithm.py", line 122, in processAlgorithm
dsm = gdal_dsm.ReadAsArray().astype(float)
File "C:\OSGeo4W\apps\Python39\lib\site-packages\osgeo\gdal.py", line 3803, in ReadAsArray
from osgeo import gdal_array
File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:\OSGeo4W\apps\Python39\lib\site-packages\osgeo\gdal_array.py", line 13, in <module>
from . import _gdal_array
File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: numpy.core.multiarray failed to import

Execution failed after 0.06 segundos
