### ISSUE TITLE
launching QGIS with UMEP returns ValueError: failed to parse CPython sys.version

### ISSUE THREAD

**Issue by s-martiz** [UMEP-dev/UMEP#569]
Hello everyone
I encounter a bug when I try to install the plugin when launching qgis. Here is the error message obtained:

```
Impossible de charger l'extension 'processing_umep' provoque une erreur lors de l'appel à sa méthode classFactory() 

ValueError: failed to parse CPython sys.version: '3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]' 
Traceback (most recent call last):
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\__init__.py", line 38, in classFactory
    from .processing_umep import ProcessingUMEPPlugin
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep.py", line 38, in 
    from .processing_umep_provider import ProcessingUMEPProvider
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep_provider.py", line 54, in 
    from .processor.urock_processing_algorithm import URockAlgorithm
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\urock_processing_algorithm.py", line 56, in 
    import pandas as pd
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\smartinez\.conda\envs\umep_pymdu\lib\site-packages\pandas\__init__.py", line 23, in 
    from pandas.compat import (
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\smartinez\.conda\envs\umep_pymdu\lib\site-packages\pandas\compat\__init__.py", line 17, in 
    from pandas.compat._constants import (
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\smartinez\.conda\envs\umep_pymdu\lib\site-packages\pandas\compat\_constants.py", line 19, in 
    PYPY = platform.python_implementation() == "PyPy"
  File "C:\Users\smartinez\.conda\envs\umep_pymdu\lib\platform.py", line 1111, in python_implementation
    return _sys_version()[0]
  File "C:\Users\smartinez\.conda\envs\umep_pymdu\lib\platform.py", line 1070, in _sys_version
    raise ValueError(
ValueError: failed to parse CPython sys.version: '3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]'


Version de Python : 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] 
Version de QGIS : 3.34.0-Prizren Prizren, exported 

Chemin Python :
C:/Users/smartinez/.conda/envs/umep_pymdu/Library/./python
C:/Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/Users/smartinez/.conda/envs/umep_pymdu/Library/./python/plugins
C:\Users\smartinez\.conda\envs\umep_pymdu\Library\python
C:\Users\smartinez\.conda\envs\umep_pymdu\Library\python\plugins
C:\Users\smartinez\Documents\TestInstall\pymdu
C:\ProgramData\anaconda3\python310.zip
C:\Users\smartinez\.conda\envs\umep_pymdu\DLLs
C:\Users\smartinez\.conda\envs\umep_pymdu\lib
C:\Users\smartinez\.conda\envs\umep_pymdu\Library\bin
C:\Users\smartinez\AppData\Roaming\Python\Python310\site-packages
C:\Users\smartinez\.conda\envs\umep_pymdu
C:\Users\smartinez\.conda\envs\umep_pymdu\lib\site-packages
C:/Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```
Here are some infos concerning my conda environment 

```
     active environment : umep_pymdu
    active env location : C:\Users\smartinez\.conda\envs\umep_pymdu
            shell level : 1
       user config file : C:\Users\smartinez\.condarc
 populated config files : C:\Users\smartinez\.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __win=0=0
       base environment : C:\ProgramData\anaconda3  (read only)
      conda av data dir : C:\ProgramData\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\anaconda3\pkgs
                          C:\Users\smartinez\.conda\pkgs
                          C:\Users\smartinez\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\smartinez\.conda\envs
                          C:\ProgramData\anaconda3\envs
                          C:\Users\smartinez\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.9 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False
           
```

**Comment by biglimp** [comment]
I see that you are using Anaconda. We have had multiple issues regarding the combined use of Anaconda and QGIS. For example, look [here](https://github.com/UMEP-dev/UMEP/issues/549). Also, try to search for old (open and closed) issues where people have tried to get similar setup as yours to work.

**Comment by s-martiz** [comment]
@biglimp
Thanks for your feedback, I looked at similar exits before creating this one. If I'm not mistaken, most bugs that occur when using Anaconda are due to bad package versions (numpy, jaydebeapi, etc). This bug seems to be a bit different. The use of UMEP with Anaconda seems to be quite interesting for large scale studies or parametric studies.

**Comment by biglimp** [comment]
ok, I see. Then I suggest that you have a look on what pandas version that you have as that seems to be the issue. @j3r3m1 and @sunt05, do we have any version requirements for pandas in Supy or URock?

**Comment by sunt05** [comment]
No specific requirement from the `supy` side - `supy` aims to be compatible with all pandas versions through their lifespan.

For this particular error, it looks to be a bug in the `platform` package shipped in this `conda` installation. 

Anyway, I would discourage the use of `conda` with QGIS-related plugins unless one really needs to and understands what is happening behind the scene.

**Comment by j3r3m1** [comment]
I would go for a reinstallation of your anaconda version and create a clean environment  dedicated to QGIS related calculations. 
Here are libraries I would recommend installing (all at the same time to avoid conflicts) at least:
numba gdal qgis shapely unidecode statsmodels jaydebeapi importlib_metadata xarray

**Comment by j3r3m1** [comment]
> inez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\urock_processing_algorithm.py", line 56, in 
>     import pandas as pd

Reading this line it seems there is an issue related to the use of pandas in URock. I look at that.

What is your pandas version ?

**Comment by s-martiz** [comment]
I changed the version of the pandas package from 2.0.0 to 1.5.3. I now have another bug that seems to be related to numpy. I'm using numpy version 1.23.4.
This is the error I get now: 
```
Impossible de charger l'extension 'processing_umep' provoque une erreur lors de l'appel à sa méthode classFactory() 

ValueError: failed to parse CPython sys.version: '3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]' 
Traceback (most recent call last):
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\__init__.py", line 38, in classFactory
    from .processing_umep import ProcessingUMEPPlugin
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep.py", line 38, in 
    from .processing_umep_provider import ProcessingUMEPProvider
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep_provider.py", line 36, in 
    from .preprocessor.wall_heightaspect_algorithm import ProcessingWallHeightAscpetAlgorithm
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\preprocessor\wall_heightaspect_algorithm.py", line 50, in 
    import numpy as np
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\smartinez\.conda\envs\umep_pymdu\lib\site-packages\numpy\__init__.py", line 140, in 
    from . import core
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\smartinez\.conda\envs\umep_pymdu\lib\site-packages\numpy\core\__init__.py", line 103, in 
    from . import _internal
  File "C:\Users/smartinez/.conda/envs/umep_pymdu/Library/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\smartinez\.conda\envs\umep_pymdu\lib\site-packages\numpy\core\_internal.py", line 19, in 
    IS_PYPY = platform.python_implementation() == 'PyPy'
  File "C:\Users\smartinez\.conda\envs\umep_pymdu\lib\platform.py", line 1111, in python_implementation
    return _sys_version()[0]
  File "C:\Users\smartinez\.conda\envs\umep_pymdu\lib\platform.py", line 1070, in _sys_version
    raise ValueError(
ValueError: failed to parse CPython sys.version: '3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]'


Version de Python : 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] 
Version de QGIS : 3.34.0-Prizren Prizren, exported 

Chemin Python :
C:/Users/smartinez/.conda/envs/umep_pymdu/Library/./python
C:/Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/Users/smartinez/.conda/envs/umep_pymdu/Library/./python/plugins
C:\Users\smartinez\.conda\envs\umep_pymdu\Library\python
C:\Users\smartinez\.conda\envs\umep_pymdu\Library\python\plugins
C:\Users\smartinez\Documents\TestInstall\pymdu
C:\ProgramData\anaconda3\python310.zip
C:\Users\smartinez\.conda\envs\umep_pymdu\DLLs
C:\Users\smartinez\.conda\envs\umep_pymdu\lib
C:\Users\smartinez\.conda\envs\umep_pymdu\Library\bin
C:\Users\smartinez\AppData\Roaming\Python\Python310\site-packages
C:\Users\smartinez\.conda\envs\umep_pymdu
C:\Users\smartinez\.conda\envs\umep_pymdu\lib\site-packages
C:/Users/smartinez/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by sunt05** [comment]
the issue lies in the `python` packaged by `conda` - see here: https://github.com/python/cpython/issues/102396

**Comment by s-martiz** [comment]
Dear all, 

I finally managed to use UMEP in a 100% python environment by carrying out the following steps:

1. Installation of OSGEO4W
2. Creation of a conda python environment = 3.9 
3. Add specific paths in the script header

Below is the script corresponding to the addition of the paths required for my installation to work. This may not be the only method but it works for me.

```
import sys
import os
QGIS_PATH = os.path.normpath("C:/OSGeo4W/apps/qgis/python")
PLUGIN_PATH = os.path.normpath("C:/OSGeo4W/apps/qgis/python/plugins")
UMEP_PLUGIN_PATH = os.path.normpath("C:/Users/simon/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/processing_umep")
UMEP_PLUGIN_PATH_2 = os.path.normpath("C:/Users/simon/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins")
QGIS_SITE_PACKAGE = os.path.normpath("C:/OSGeo4W/apps/Python39/lib/site-packages")

sys.path.append(QGIS_PATH)
sys.path.append(PLUGIN_PATH)
sys.path.append(UMEP_PLUGIN_PATH_2)
sys.path.append(UMEP_PLUGIN_PATH)
sys.path.append(QGIS_SITE_PACKAGE)
```
Best regards

**Comment by biglimp** [comment]
@simonmarti1992 , would it be ok to transfer this to Discussions so that others can see your set up?

**Comment by s-martiz** [comment]
@biglimp, of course, no problem
