### ISSUE TITLE
Enabling UMEP plugin leads to QGIS crashes

### ISSUE THREAD

**Issue by Guts** [UMEP-dev/UMEP#590]
**Describe the bug**

I wanted to experiment the plugin and include it in a course I give in an university but after installing it then its dependencies, the plugin makes QGIS crash :/.

Again when I restart QGIS and I enable the plugin in the extensions manager.

**To Reproduce**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - QGIS Version 3.28.15
 - UMEP Version 4.0.4
 - SuPy Version ?

**Screenshots**

No screenshots since QGIS is closing itself but I've launched it from the command-line to retrieve some information:

```sh
QGIS died on signal 11[New LWP 18333]
[New LWP 18334]
[New LWP 18336]
[New LWP 18337]
[New LWP 18338]
[New LWP 18352]
[New LWP 18353]
[New LWP 18354]
[New LWP 18355]
[New LWP 18356]
[New LWP 18357]
[New LWP 18358]
[New LWP 18359]
[New LWP 18360]
[New LWP 18361]
[New LWP 18362]
[New LWP 18366]
[New LWP 18368]
[New LWP 18384]
[New LWP 18385]
[New LWP 18386]
[New LWP 18387]
[New LWP 18388]
[New LWP 18389]
[New LWP 18390]
[New LWP 18391]
[New LWP 18393]
[New LWP 18394]
[New LWP 18397]
[New LWP 18398]
[New LWP 18399]
[New LWP 18400]
[New LWP 18401]
[New LWP 18402]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f3592cea42f in __GI___wait4 (pid=18411, stat_loc=0x55bf685f5bac, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	../sysdeps/unix/sysv/linux/wait4.c: Aucun fichier ou dossier de ce nom.
[Current thread is 1 (Thread 0x7f3582ae3240 (LWP 18330))]
#0  0x00007f3592cea42f in __GI___wait4 (pid=18411, stat_loc=0x55bf685f5bac, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
        sc_ret = -512
        sc_cancel_oldtype = 0
#1  0x000055bf63f54a7c in  ()
#2  0x00007f3592c42520 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#3  __pthread_kill_implementation (no_tid=0, signo=11, threadid=139867802448448) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7f3582ae3240
        old_mask = {__val = {15591563342419970047, 139865749136688, 513, 51, 93459330642192, 2, 139864175029344, 139867802446112, 11, 139864173170898, 51, 2, 139864175029344, 139864172018719, 2286835204096, 28272841996671858}}
        ret = <optimized out>
#4  __pthread_kill_internal (signo=11, threadid=139867802448448) at ./nptl/pthread_kill.c:78
#5  __GI___pthread_kill (threadid=139867802448448, signo=signo@entry=11) at ./nptl/pthread_kill.c:89
#6  0x00007f3592c42476 in __GI_raise (sig=11) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#7  0x00007f3592c42520 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#8  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#9  0x00007f3592ca8583 in __GI___strdup (s=0x0) at ./string/strdup.c:41
        len = <optimized out>
        new = <optimized out>
#10 0x00007f3588cde636 in NC_rcfile_insert () at /lib/x86_64-linux-gnu/libnetcdf.so.19
#11 0x00007f3560858b0b in nc_rc_set () at /home/jmo/.local/lib/python3.10/site-packages/netCDF4/../netCDF4.libs/libnetcdf-d25a76e9.so.19
#12 0x00007f3560c8eb92 in  () at /home/jmo/.local/lib/python3.10/site-packages/netCDF4/_netCDF4.cpython-310-x86_64-linux-gnu.so
#13 0x00007f34aa32972e in PyModule_ExecDef () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#14 0x00007f34aa3e8583 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#15 0x00007f34aa32868e in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#16 0x00007f34aa276776 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#17 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#18 0x00007f34aa27b9c8 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#19 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#20 0x00007f34aa279efe in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#21 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#22 0x00007f34aa27863e in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#23 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#24 0x00007f34aa27863e in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#25 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#26 0x00007f34aa2e13f4 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#27 0x00007f34aa2e175f in _PyObject_CallMethodIdObjArgs () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#28 0x00007f34aa3eb2a4 in PyImport_ImportModuleLevelObject () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#29 0x00007f34aa3be2fe in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#30 0x00007f34aa328023 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#31 0x00007f34aa2dfadc in _PyObject_MakeTpCall () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#32 0x00007f34aa27c28a in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#33 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#34 0x00007f34aa277857 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#35 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#36 0x00007f34aa3bd3de in PyEval_EvalCode () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#37 0x00007f34aa3bd96d in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#38 0x00007f34aa3287b3 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#39 0x00007f34aa276776 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#40 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#41 0x00007f34aa27b9c8 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#42 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#43 0x00007f34aa279efe in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#44 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#45 0x00007f34aa27863e in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#46 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#47 0x00007f34aa27863e in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#48 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#49 0x00007f34aa2e13f4 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#50 0x00007f34aa2e175f in _PyObject_CallMethodIdObjArgs () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#51 0x00007f34aa3eb2a4 in PyImport_ImportModuleLevelObject () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#52 0x00007f34aa3be2fe in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#53 0x00007f34aa328023 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#54 0x00007f34aa2dfadc in _PyObject_MakeTpCall () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#55 0x00007f34aa27c28a in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#56 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#57 0x00007f34aa277857 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#58 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#59 0x00007f34aa3bd3de in PyEval_EvalCode () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#60 0x00007f34aa3bd96d in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#61 0x00007f34aa3287b3 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#62 0x00007f34aa276776 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#63 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#64 0x00007f34aa27b9c8 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#65 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#66 0x00007f34aa279efe in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#67 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#68 0x00007f34aa27863e in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#69 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#70 0x00007f34aa27863e in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#71 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#72 0x00007f34aa2e13f4 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#73 0x00007f34aa2e175f in _PyObject_CallMethodIdObjArgs () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#74 0x00007f34aa3eb2a4 in PyImport_ImportModuleLevelObject () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#75 0x00007f34aa3be2fe in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#76 0x00007f34aa328023 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#77 0x00007f34aa2dfadc in _PyObject_MakeTpCall () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#78 0x00007f34aa27c28a in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#79 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#80 0x00007f34aa277857 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#81 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#82 0x00007f34aa3bd3de in PyEval_EvalCode () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#83 0x00007f34aa3bd96d in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#84 0x00007f34aa3287b3 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#85 0x00007f34aa276776 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#86 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#87 0x00007f34aa27b9c8 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#88 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#89 0x00007f34aa279efe in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#90 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#91 0x00007f34aa27863e in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#92 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#93 0x00007f34aa27863e in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#94 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#95 0x00007f34aa2e13f4 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#96 0x00007f34aa2e175f in _PyObject_CallMethodIdObjArgs () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#97 0x00007f34aa3eb2a4 in PyImport_ImportModuleLevelObject () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#98 0x00007f34aa3be2fe in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#99 0x00007f34aa328023 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#100 0x00007f34aa2dfadc in _PyObject_MakeTpCall () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#101 0x00007f34aa27c28a in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#102 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#103 0x00007f34aa277857 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#104 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#105 0x00007f34aa3bd3de in PyEval_EvalCode () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#106 0x00007f34aa3bd96d in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#107 0x00007f34aa3287b3 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#108 0x00007f34aa276776 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#109 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#110 0x00007f34aa27b9c8 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#111 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#112 0x00007f34aa279efe in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#113 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#114 0x00007f34aa27863e in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#115 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#116 0x00007f34aa27863e in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#117 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#118 0x00007f34aa2e13f4 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#119 0x00007f34aa2e175f in _PyObject_CallMethodIdObjArgs () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#120 0x00007f34aa3eb2a4 in PyImport_ImportModuleLevelObject () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#121 0x00007f34aa3be2fe in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#122 0x00007f34aa328023 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#123 0x00007f34aa2dfadc in _PyObject_MakeTpCall () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#124 0x00007f34aa27c28a in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#125 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#126 0x00007f34aa277857 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#127 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#128 0x00007f34aa27b9c8 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#129 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#130 0x00007f34aa27863e in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#131 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#132 0x00007f34aa27b9c8 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#133 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#134 0x00007f34aa3bd3de in PyEval_EvalCode () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#135 0x00007f34aa40c4cd in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#136 0x00007f34aa40d4f9 in PyRun_StringFlags () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#137 0x00007f3508526c81 in  () at /usr/lib/libqgispython.so.3.28.15
#138 0x00007f350852524d in  () at /usr/lib/libqgispython.so.3.28.15
#139 0x00007f35987935ca in QgsPluginRegistry::loadPythonPlugin(QString const&) () at /lib/libqgis_app.so.3.28.15
#140 0x00007f35989b4852 in  () at /lib/libqgis_app.so.3.28.15
#141 0x00007f35989bfd11 in  () at /lib/libqgis_app.so.3.28.15
#142 0x00007f35958f1793 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#143 0x00007f3596129963 in QStandardItemModel::itemChanged(QStandardItem*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#144 0x00007f359612c44c in  () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#145 0x00007f35958f17c8 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#146 0x00007f3595852a39 in QAbstractItemModel::dataChanged(QModelIndex const&, QModelIndex const&, QVector<int> const&) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#147 0x00007f359612c194 in  () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#148 0x00007f359612ca38 in QStandardItem::setData(QVariant const&, int) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#149 0x00007f359612fc10 in QStandardItemModel::setData(QModelIndex const&, QVariant const&, int) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#150 0x00007f3595883c8a in QSortFilterProxyModel::setData(QModelIndex const&, QVariant const&, int) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#151 0x00007f359680fc39 in QStyledItemDelegate::editorEvent(QEvent*, QAbstractItemModel*, QStyleOptionViewItem const&, QModelIndex const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#152 0x00007f35967e6165 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#153 0x00007f35967ebe5a in QAbstractItemView::edit(QModelIndex const&, QAbstractItemView::EditTrigger, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#154 0x00007f35967e6546 in QAbstractItemView::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#155 0x00007f359682eae3 in QListView::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#156 0x00007f35965af4ee in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#157 0x00007f359665d422 in QFrame::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#158 0x00007f35958b9b9a in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#159 0x00007f359656c702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#160 0x00007f3596574364 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#161 0x00007f3593f4d0b3 in QgsApplication::notify(QObject*, QEvent*) () at /lib/libqgis_core.so.3.28.15
#162 0x00007f35958b9e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#163 0x00007f3596572e47 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#164 0x00007f35965c8d40 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#165 0x00007f35965cbfd5 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#166 0x00007f359656c713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#167 0x00007f3593f4d0b3 in QgsApplication::notify(QObject*, QEvent*) () at /lib/libqgis_core.so.3.28.15
#168 0x00007f35958b9e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#169 0x00007f3595d41307 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#170 0x00007f3595d16a2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#171 0x00007f3581cf8d6e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#172 0x00007f358c31bd3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#173 0x00007f358c371258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#174 0x00007f358c3193e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#175 0x00007f35959130b8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#176 0x00007f35958b875b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#177 0x00007f359677d4e2 in QDialog::exec() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#178 0x00007f34a8e06523 in  () at /usr/lib/python3/dist-packages/qgis/_gui.cpython-310-x86_64-linux-gnu.so
#179 0x00007f34aa328023 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#180 0x00007f34aa2dfadc in _PyObject_MakeTpCall () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#181 0x00007f34aa27ba1c in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#182 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#183 0x00007f34aa2e23d8 in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#184 0x00007f34aa27b9c8 in _PyEval_EvalFrameDefault () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#185 0x00007f34aa3c23af in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#186 0x00007f34aa3bd3de in PyEval_EvalCode () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#187 0x00007f34aa40c4cd in  () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#188 0x00007f34aa40d4f9 in PyRun_StringFlags () at /lib/x86_64-linux-gnu/libpython3.10.so.1.0
#189 0x00007f350852663e in  () at /usr/lib/libqgispython.so.3.28.15
#190 0x00007f350852a27a in  () at /usr/lib/libqgispython.so.3.28.15
#191 0x00007f35985b7316 in  () at /lib/libqgis_app.so.3.28.15
#192 0x00007f3594108f86 in QgsPythonRunner::run(QString const&, QString const&) () at /lib/libqgis_core.so.3.28.15
#193 0x00007f359852f9fd in QgisApp::showPluginManager() () at /lib/libqgis_app.so.3.28.15
#194 0x00007f35958f1793 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#195 0x00007f3596565be6 in QAction::triggered(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#196 0x00007f35965688fc in QAction::activate(QAction::ActionEvent) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#197 0x00007f35966f3142 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#198 0x00007f35966fad39 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#199 0x00007f35965af4ee in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#200 0x00007f359656c713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#201 0x00007f3596574364 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#202 0x00007f3593f4d0b3 in QgsApplication::notify(QObject*, QEvent*) () at /lib/libqgis_core.so.3.28.15
#203 0x00007f35958b9e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#204 0x00007f3596572e47 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#205 0x00007f35965c9843 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#206 0x00007f35965cbfd5 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#207 0x00007f359656c713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#208 0x00007f3593f4d0b3 in QgsApplication::notify(QObject*, QEvent*) () at /lib/libqgis_core.so.3.28.15
#209 0x00007f35958b9e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#210 0x00007f3595d41307 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#211 0x00007f3595d16a2c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#212 0x00007f3581cf8d6e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#213 0x00007f358c31bd3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#214 0x00007f358c371258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#215 0x00007f358c3193e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#216 0x00007f35959130b8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#217 0x00007f35958b875b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#218 0x00007f35958c0cf4 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#219 0x000055bf63f512df in  ()
#220 0x00007f3592c29d90 in __libc_start_call_main (main=main@entry=0x55bf63f4e960, argc=argc@entry=1, argv=argv@entry=0x7ffd3ab9d278) at ../sysdeps/nptl/libc_start_call_main.h:58
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 891214776070999947, 140725588710008, 94280504109408, 94280504451576, 139868177444928, -890500590605922421, -993854501213401205}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x55bf63fa3008, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1677340680}}}
        not_first_call = <optimized out>
#221 0x00007f3592c29e40 in __libc_start_main_impl (main=0x55bf63f4e960, argc=1, argv=0x7ffd3ab9d278, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd3ab9d268) at ../csu/libc-start.c:392
#222 0x000055bf63f53c85 in  ()
[Inferior 1 (process 18330) detached]
gdb returned 0
Abandon (core dumped)

```

**Data**
If applicable, add data files to help us reproduce your problem.

**Additional context**

**Comment by j3r3m1** [comment]
Hi Guts,
Thank you for reporting. Can you tell more about how you install QGIS and deal with Python libraries in Linux ? Using pip ? anaconda ?

**Comment by Guts** [comment]
Sure.

QGIS is installed through apt and official LTR PPA.

Python libraries are usually installed through system pip. But the plugin is supposed to install them by itself, isn't?

**Comment by j3r3m1** [comment]
Yes it is. Even though it is not the "official" way to solve the issue you are encountering, you might have a try installing QGIS via anaconda.

In this conversation, you have an example where of quite similar crash that was solved using conda: https://github.com/UMEP-dev/UMEP/issues/584#issuecomment-1898164634

**Comment by Guts** [comment]
Thanks for your inputs bud sadly, I'm not willing to use conda on my system to fit a QGIS plugin requirements. I'll try it later if the setup got easier or if I find more project motivating the installation of conda  :).
