### ISSUE TITLE
Python error when running the 

### ISSUE THREAD

**Issue by lkarch** [UMEP-dev/UMEP#592]
**Describe the bug**
Hello, 

I have an issue when running the "Urban Morphology: Morphometric Calculator (Point)" model. Everytime I run the model I get the following error: 

Traceback (most recent call last):
File "/Users/user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/processing_umep/preprocessor/imagemorphparmspoint_algorithm.py", line 247, in processAlgorithm
immorphresult = morph.imagemorphparam_v2(dsm, dem, scale, 1, degree, feedback, 1)
File "/Users/user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/processing_umep/util/imageMorphometricParms_v2.py", line 100, in imagemorphparam_v2
lineMid = a[0:imidy,imid]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

 This is the case when using QGIS 3.34.4 on MacOS and QGIS 3.28.9 on Windows 10  
with UMEP for processing version 2.0.13

Here is a screenshot of the dialog box: 
<img width="1470" alt="Capture d’écran 2024-03-20 à 15 49 02" src="https://github.com/UMEP-dev/UMEP/assets/72600098/487f8b80-af6b-47d8-a364-e6a017278050">

**Comment by lkarch** [comment]
Here are the link to the geodata I used: https://enacshare.epfl.ch/dvLydJZUjoT26atPQFqM5
