### ISSUE TITLE
Meteorological Data: Download data (ERA5)  Missing/incomplete configuration file

### ISSUE THREAD

**Issue by CDelasse** [UMEP-dev/UMEP#599]
I got this error when I tried to download meteorological data for a POI for 1 day :
Traceback (most recent call last):
File "C:\Users/cdelasse01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\preprocessor\copernicusera5_algorithm.py", line 182, in processAlgorithm
sp.util.gen_forcing_era5(lat, lon, startDate, endDate, hgt_agl_diag=diagHeight, dir_save=Path(outputDir))
File "C:\Users\cdelasse01\AppData\Roaming\Python\Python39\site-packages\supy\util\_era5.py", line 733, in gen_forcing_era5
list_fn_sfc, list_fn_ml = load_filelist_era5(
File "C:\Users\cdelasse01\AppData\Roaming\Python\Python39\site-packages\supy\util\_era5.py", line 627, in load_filelist_era5
download_era5(
File "C:\Users\cdelasse01\AppData\Roaming\Python\Python39\site-packages\supy\util\_era5.py", line 523, in download_era5
download_cds(path_dir_save / fn_sfc, dict_req)
File "C:\Users\cdelasse01\AppData\Roaming\Python\Python39\site-packages\supy\util\_era5.py", line 445, in download_cds
c = cdsapi.Client()
File "C:\Users\cdelasse01\AppData\Roaming\Python\Python39\site-packages\cdsapi\api.py", line 273, in __init__
raise Exception('Missing/incomplete configuration file: %s' % (dotrc))
Exception: Missing/incomplete configuration file: C:\Users\cdelasse01/.cdsapirc

Execution failed after 0.15 secondes

QGIS version : 3.32 Lima
Supy version : 2022.4.7
Thanks in advance

**Comment by biglimp** [comment]
You need to get a configuration file that works. See here for instructions (https://umep-docs.readthedocs.io/en/latest/pre-processor/Meteorological%20Data%20Download%20data%20%28ERA5%29.html#)
