### ISSUE TITLE
Python warning when running the Footprint model (Source Area Model (Point))

### ISSUE THREAD

**Issue by lkarch** [UMEP-dev/UMEP#602]
Hello,

I have an issue when running the Footprint model. When setting the values directly inside the dialog box, the algorithm does not encounter any issues and works perfectly fine. Now I would like to use an input file with associated time stamps, but after a while, I get the following warning: 

2024-04-17T11:50:54     WARNING    Traceback (most recent call last):
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\FootprintModel\footprint_model.py", line 578, in start_process
              fp.footprintiterKLJ(iterations=it,z_0_input=z_0_input,z_d_input=z_d_input,z_ag=z_m_input,sigv=sigv,
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\FootprintModel\KingsFootprint_UMEP.py", line 293, in footprintiterKLJ
              FFP = FFP_climatology(zm=z_m, z0=z_0, umean=None, h=hbl, ol=L, sigmav=sig_v, ustar=u_star,
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\FootprintModel\KingsFootprint_UMEP.py", line 613, in FFP_climatology
              sigystar_dummy[px] = (ac * np.sqrt(bc * np.abs(xstar_ci_dummy[px])**2 / (1 +
             UnboundLocalError: local variable 'xstar_ci_dummy' referenced before assignment

And the run never ends.
I have attached the input file I use. 
[input_parameters.txt](https://github.com/UMEP-dev/UMEP-processing/files/15009339/input_parameters.txt)

I am currently using QGIS 3.28.9 on Windows 10 with UMEP version 4.0.4.

**Comment by biglimp** [comment]
What raster data (london test data?) are you using and what footprint model (Kjiun?) was selected?

**Comment by lkarch** [comment]
I was using my own data and Kjlun method. I just tried with the London test data and it seems to work fine. There must be a problem with my DSM and DEM files (could their extent be too small?). I'll try to fix it.

**Comment by biglimp** [comment]
Did you solve this? Can I close?

**Comment by biglimp** [comment]
I am closing this. Start a new issue if this error still exists or start a Discussion.
