### ISSUE TITLE
Problem in running the SUEWS simple

### ISSUE THREAD

**Issue by marciaamatias** [UMEP-dev/UMEP#608]
Hi everyone 

So I finally manage to prepare all data needed to the SUEWS simple. 

However, when running the model this error appears (see image please)

![error](https://github.com/UMEP-dev/UMEP/assets/35871620/fc62cb68-7286-450f-ac01-d4cffcf2246a)

Can you help me? What name is the error referring? 

And what about the Supy?

I get this message:

2024-04-28 12:32:00,423 - SuPy - INFO - All cache cleared.
2024-04-28 12:32:01,053 - SuPy - ERROR - C:\Users\marci\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\UMEP\suewsmodel\Input\GridLayoutTel.nml does not exists!
Traceback (most recent call last):
  File "C:\Users\marci\AppData\Roaming\Python\Python39\site-packages\supy\_load.py", line 278, in load_SUEWS_nml
    df_nml = pd.DataFrame(parser.read(p_nml))
  File "C:\Users\marci\AppData\Roaming\Python\Python39\site-packages\f90nml\parser.py", line 279, in read
    nml_file = open(nml_fname, 'r') if nml_is_path else nml_fname
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\marci\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\UMEP\\suewsmodel\\Input\\GridLayoutTel.nml'

Thank you in advance!

**Comment by biglimp** [comment]
How did you generate your input data?

**Comment by marciaamatias** [comment]
This is now solved.
