### ISSUE TITLE
UMEP couldn't install python packages 

### ISSUE THREAD

**Issue by marciaamatias** [UMEP-dev/UMEP#619]
Hello 

Are you having problems with the version 3.36.3-Maidenhead? I tried to install the UMEP for processing in the new version so I could run again the SUEWS model but it doesn't work 

![image](https://github.com/UMEP-dev/UMEP/assets/35871620/93a8734d-e0be-45c6-a9bd-970b522a8404)

This is the message on the General Tab

2024-05-27T11:43:36     WARNING    Traceback (most recent call last):
              File "C:\Users/marci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\__init__.py", line 18, in 
              import supy as sp
              File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             ModuleNotFoundError: No module named 'supy'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/marci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\umep_installer.py", line 129, in setup_umep_python
              import supy as sp
              File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             ModuleNotFoundError: No module named 'supy'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/marci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\__init__.py", line 38, in 
              setup_umep_python(ver=None)
              File "C:\Users/marci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\umep_installer.py", line 136, in setup_umep_python
              install_umep_python(ver)
              File "C:\Users/marci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\umep_installer.py", line 90, in install_umep_python
              str_info = subprocess.check_output(
              ^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\subprocess.py", line 466, in check_output
              return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\subprocess.py", line 571, in run
              raise CalledProcessError(retcode, process.args,
             subprocess.CalledProcessError: Command '['C:\\PROGRA~1\\QGIS33~1.3\\apps\\Python312\\..\\..\\bin\\pythonw.exe', '-m', 'pip', 'install', 'umep-reqs', '-U', '--user', '--prefer-binary']' returned non-zero exit status 1.

**Comment by j3r3m1** [comment]
Hi @marciaamatias ,
This is indeed a known problem (https://github.com/UMEP-dev/UMEP/discussions/612). We are working on solving this.

**Comment by wangguo-ops** [comment]
how do you solve it?

**Comment by kun-creator** [comment]
I have some troubles too/ #![Image](https://github.com/user-attachments/assets/41828e61-0679-4812-ad6c-1256f18f8674)
