### ISSUE TITLE
URockv2023a suddenly not working

### ISSUE THREAD

**Issue by Cas6713** [UMEP-dev/UMEP#621]
I was using URock before and it was fine. Now it crashes midway and i cannot understand the error:

Error:
Traceback (most recent call last):
File "JdbcPreparedStatement.java", line 237, in org.h2.jdbc.JdbcPreparedStatement.execute
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\atrip\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 534, in execute
is_rs = self._prep.execute()
org.h2.jdbc.org.h2.jdbc.JdbcSQLSyntaxErrorException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "NAN" not found; SQL statement:

INSERT INTO TEMPO_VERTICAL_PROFILE_WIND_20240530204600 VALUES (1,nan), (2,nan), (3,nan), (4,nan), (5,nan), (6,nan), (7,nan), (8,nan), (9,nan), (10,nan), (11,nan), (12,nan), (13,nan), (14,nan), (15,nan), (16,nan), (17,nan), (18,nan), (19,nan), (20,nan), (21,nan), (22,nan), (23,nan), (24,nan), (25,nan), (26,nan), (27,nan), (28,nan), (29,nan), (30,nan), (31,nan), (32,nan), (33,nan);
[42122-200]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\urock_processing_algorithm.py", line 447, in processAlgorithm
MainCalculation.main(javaEnvironmentPath = javaEnvVar,
File "C:\Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\MainCalculation.py", line 600, in main
InitWindField.setInitialWindField(cursor = cursor,
File "C:\Users/atrip/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\URock\InitWindField.py", line 2957, in setInitialWindField
cursor.execute("""
File "C:\Users\atrip\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 536, in execute
_handle_sql_exception()
File "C:\Users\atrip\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 165, in _handle_sql_exception_jpype
reraise(exc_type, exc_info[1], exc_info[2])
File "C:\Users\atrip\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 57, in reraise
raise value.with_traceback(tb)
File "C:\Users\atrip\AppData\Roaming\Python\Python39\site-packages\jaydebeapi\__init__.py", line 534, in execute
is_rs = self._prep.execute()
jaydebeapi.DatabaseError: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "NAN" not found; SQL statement:

INSERT INTO TEMPO_VERTICAL_PROFILE_WIND_20240530204600 VALUES (1,nan), (2,nan), (3,nan), (4,nan), (5,nan), (6,nan), (7,nan), (8,nan), (9,nan), (10,nan), (11,nan), (12,nan), (13,nan), (14,nan), (15,nan), (16,nan), (17,nan), (18,nan), (19,nan), (20,nan), (21,nan), (22,nan), (23,nan), (24,nan), (25,nan), (26,nan), (27,nan), (28,nan), (29,nan), (30,nan), (31,nan), (32,nan), (33,nan);
[42122-200]

Execution failed after 126.56 seconds (2 minutes 7 seconds)

**Desktop (please complete the following information):**
 - OS: Win11
 - QGIS Version 3.22

I am using DEM, and weather files that i have used before and got results. It is failing on repeating.

**Comment by j3r3m1** [comment]
Hi,
Can you share the input parameters and files (build, vegetation and meteo if any) of the process ?
Jérémy

**Comment by j3r3m1** [comment]
@Cas6713 are you still facing the problem ?
