### ISSUE TITLE
Error in installing UMEP

### ISSUE THREAD

**Issue by yaogan2024** [UMEP-dev/UMEP#638]
Hello,

I am trying to install UMEP plug in in the QGIS but coudn't install Python packages. 

Desktop (please complete the following information):
OS: Windows
QGIS Version [e.g. 3.34.9]

here is the warning:
WARNING    Exception
             
             The above exception was the direct cause of the following exception:
             
             Traceback (most recent call last):
              File "C:\Users/DA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\suewsmodel\__init__.py", line 36, in 
              setup_supy(ver=None)
              File "C:\Users/DA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\suewsmodel\supy_installer.py", line 134, in setup_supy
              install_supy(ver)
              File "C:\Users/DA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\suewsmodel\supy_installer.py", line 103, in install_supy
              raise RuntimeError(f"UMEP couldn't install supy{str_ver}!") from Exception
             RuntimeError: UMEP couldn't install supy!

**Comment by biglimp** [comment]
What version of windows, QGIS and UMEP are you trying to install?
