### ISSUE TITLE
[umep:Outdoor Thermal Comfort: SOLWEIG] TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by ccatter** [UMEP-dev/UMEP#663]
SOLWEIG works well with GUI.
However, when I switched to python console, the task failed with the following error:
```
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\tools\general.py", line 109, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\core\Processing.py", line 192, in runAlgorithm
    ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 70, in execute
    results, ok = alg.run(parameters, context, feedback, {}, False)
_core.QgsProcessingException: Traceback (most recent call last):
  File "C:\Users/yehuang/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processor\solweig_algorithm.py", line 1011, in processAlgorithm
    dRad, Kside = so.Solweig_2022a_calc(
  File "C:\Users/yehuang/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\SOLWEIGpython\Solweig_2022a_calc_forprocessing.py", line 196, in Solweig_2022a_calc
    gvfalbnoshW, gvfLupN, gvfalbN, gvfalbnoshN, gvfSum, gvfNorm = gvf_2018a(wallsun, walls, buildings, scale, shadow, first,
  File "C:\Users/yehuang/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\functions\SOLWEIGpython\gvf_2018a.py", line 29, in gvf_2018a
    sunwall = (wallsun / walls * buildings) == 1  # new as from 2015a
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```

The parameter and the dataset is as followed:
```
#run SOLWEIG
file_name = 'N166885_E150740'
p = 'C:/Users/yehuang/OneDrive - UCL/python/data/Bicycle_counting_points/DSM_split/'+file_name
if not os.path.exists(p+'/results_'+file_name):
  os.makedirs(p+'/results_'+file_name)
  print('Create path.')
else:
  print('Path already exists.')

params = {
    'ABS_L' : 0.95, 
    'ABS_S' : 0.7, 
    'ACTIVITY' : 80, 
    'AGE' : 35, 
    'ALBEDO_GROUND' : 0.15, 
    'ALBEDO_WALLS' : 0.2, 
    'CLO' : 0.9, 
    'CONIFER_TREES' : True, 
    'CYL' : True, 
    'EMIS_GROUND' : 0.95, 
    'EMIS_WALLS' : 0.9, 
    'HEIGHT' : 180, 
    'INPUTMET' : 'C:/Users/yehuang/OneDrive - UCL/python/data/meteorology/Brussels/Meto_brussels_TMYx.txt', 
    'INPUT_ANISO' : p+'/shadowmats.npz', 
    'INPUT_ASPECT' : p+'/Wall_aspect_'+file_name+'.tif', 
    'INPUT_CDSM' : p+'/Vegetation_'+file_name+'.tif', 
    'INPUT_DEM' : p+'/Ground_'+file_name+'.tif', 
    'INPUT_DSM' : p+'/Ground_Building_'+file_name+'.tif', 
    'INPUT_HEIGHT' : p+'/Wall_height_'+file_name+'.tif', 
    'INPUT_LC' : None, 
    'INPUT_SVF' : p+'/svfs.zip', 
    'INPUT_TDSM' : None, 
    'INPUT_THEIGHT' : 25, 
    'LEAF_END' : 300, 
    'LEAF_START' : 97, 
    'ONLYGLOBAL' : True, 
    'OUTPUT_DIR' : p+'/results_'+file_name, 
    'OUTPUT_KDOWN' : False, 
    'OUTPUT_KUP' : False, 
    'OUTPUT_LDOWN' : False, 
    'OUTPUT_LUP' : False, 
    'OUTPUT_SH' : False, 
    'OUTPUT_TMRT' : True, 
    'OUTPUT_TREEPLANTER' : False, 
    'POI_FIELD' : '', 
    'POI_FILE' : None, 
    'POSTURE' : 0, 
    'SAVE_BUILD' : True, 
    'SENSOR_HEIGHT' : 10, 
    'SEX' : 0, 
    'TRANS_VEG' : 3, 
    'USE_LC_BUILD' : False, 
    'UTC' : 0, 
    'WEIGHT' : 75 }
processing.run("umep:Outdoor Thermal Comfort: SOLWEIG", params)
```
[N166885_E150740.zip](https://github.com/user-attachments/files/17529795/N166885_E150740.zip)

**Comment by biglimp** [comment]
Did you compare your params variable with the successful run from the GUI? You find it in History (Clock) in the Processing Panel.

**Comment by ccatter** [comment]
@biglimp Many thanks for your rapid response. I found out that I accidently set ['USE_LC_BUILD' : True,] without land use input in python console (checked "use land cover grid to derive building grid." option in the GUI). Thank you again for the hint.
