### ISSUE TITLE
Download data (ERA5) error, OSX binary install

### ISSUE THREAD

**Issue by CsillaVG** [UMEP-dev/UMEP#683]
Hi Team!
Here comes my 1/3 bug report, related to the ERA5 data downloader.
Thank you!

Action ::
Attempting to run Meteorological Data: Download data (ERA5) from the processing toolbox runs into error before even sending over the request to Copernicus (no request in the queue).

Environment ::
```
macOS Ventura 13.2 running with M1
QGIS version: 3.40.1-Bratislava
Python version: 3.9.5
UMEP 4.1.1
UMEP for processing 2.0.35
SuPy version: 2024.5.24.dev
```

Error message (output from the Pre-Processor interface) ::
```python
Algorithm started at: 2024-12-12T10:35:30
Algorithm 'Meteorological Data: Download data (ERA5)' starting…
Input parameters:
{ 'CRS' : QgsCoordinateReferenceSystem('EPSG:4326'), 'DATEINIEND' : '2020-12-31T00:00:00', 'DATEINISTART' : '2020-01-01T00:00:00', 'DIAG_HEIGHT' : 2, 'INPUT_POINT' : '1.5,43.5 [EPSG:4326]', 'OUTPUT_DIR' : '/Users/vuk/Library/CloudStorage/Dropbox/eXchange/QGISprojects/Toulouse/_ERA5data/2020' }

SuPy version: 2024.5.24.dev
INPUT PARAMETERS:
lat = 1.5
lon = 43.5
Start = 2020-01-01T00:00:00
End = 2020-12-31T00:00:00
Diagnostic height = 2.0
Output folder = /Users/vuk/Library/CloudStorage/Dropbox/eXchange/QGISprojects/Toulouse/_ERA5data/2020
Traceback (most recent call last):
File "/Users/vuk/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/processing_umep/preprocessor/copernicusera5_algorithm.py", line 182, in processAlgorithm
sp.util.gen_forcing_era5(lat, lon, startDate, endDate, hgt_agl_diag=diagHeight, dir_save=Path(outputDir))
File "/Users/vuk/.local/lib/python3.9/site-packages/supy/util/_era5.py", line 733, in gen_forcing_era5
list_fn_sfc, list_fn_ml = load_filelist_era5(
File "/Users/vuk/.local/lib/python3.9/site-packages/supy/util/_era5.py", line 627, in load_filelist_era5
download_era5(
File "/Users/vuk/.local/lib/python3.9/site-packages/supy/util/_era5.py", line 523, in download_era5
download_cds(path_dir_save / fn_sfc, dict_req)
File "/Users/vuk/.local/lib/python3.9/site-packages/supy/util/_era5.py", line 455, in download_cds
c.retrieve(**dict_req)
File "/Users/vuk/.local/lib/python3.9/site-packages/cdsapi/api.py", line 348, in retrieve
result = self._api("%s/resources/%s" % (self.url, name), request, "POST")
File "/Users/vuk/.local/lib/python3.9/site-packages/cdsapi/api.py", line 417, in _api
result = self.robust(action)(
File "/Users/vuk/.local/lib/python3.9/site-packages/cdsapi/api.py", line 606, in wrapped
r = call(*args, **kwargs)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/requests/sessions.py", line 578, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/requests/sessions.py", line 516, in request
prep = self.prepare_request(req)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/requests/sessions.py", line 449, in prepare_request
p.prepare(
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/requests/models.py", line 318, in prepare
self.prepare_auth(auth, url)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/requests/models.py", line 549, in prepare_auth
r = auth(self)
TypeError: 'tuple' object is not callable

Execution failed after 0.65 seconds

Loading resulting layers
Algorithm 'Meteorological Data: Download data (ERA5)' finished
```

**Comment by biglimp** [comment]
Did you try to download outside of QGIS/UMEP and if so, did it work?
As stated in the manual, the cdsapi can be very slow.

**Comment by sunt05** [comment]
Appears to be a network or upstream package issue.

Hi @CsillaVG, is this issue still persisting after several attempts?

**Comment by CsillaVG** [comment]
Unfortunately, it does. No matter what I do. 
IMHO, some of the problems stem from the fact that the binary install for MacOS comes with Python: 3.9.5.

**Comment by sunt05** [comment]
I noticed your other issue #685. Since netCDF files can be successfully downloaded, there's no issue with cdsapi or supy. The issue seems to be network-related—perhaps some SSH checks haven't been completed for this Python installation. Anyway, as long as you have a working Python setup (e.g., the one in #685), just go with that one.

**Comment by CsillaVG** [comment]
Update: No matter what I do, the ERA5 downloaded under the default QGIS binary installation with stable/long term UMEP release ends in the above "TypeError: 'tuple' object is not callable".

When updating UMEP to developmental version, the "SyntaxError: f-string: unmatched '['" bug shows up. The latter issue can only be taken care of by updating python to 3.12 ([see](https://github.com/UMEP-dev/UMEP/issues/687#issuecomment-2556122375)).

I'd perhaps consider this issue closed. Until [QGIS releases an installer bundled with a more recent python](https://github.com/qgis/QGIS/issues/54491), Mac users (esp on newer machines) are recommend installing UMEP into a python 3.12 environment via [conda](https://aneto.pt/posts/tutorials/2019-05-29-using-qgis-from-conda/) or [MacPorts](https://www.qgis.org/resources/installation-guide/#macports).
