### ISSUE TITLE
Download data (ERA5) error, Windows

### ISSUE THREAD

**Issue by CsillaVG** [UMEP-dev/UMEP#684]
Bug report 2/3

Action ::
The attempt to run Meteorological Data: Download data (ERA5) from the processing toolbox results in error. Single request to Copernicus is sent, (single) data generated, but never downloaded. The process exists with the below error message.

Environment ::
Windows 11 Pro
QGIS version: 3.34.13-Prizren
Python version: 3.12.7
UMEP 4.1.1
UMEP for processing 2.0.35
SuPy version: 2024.5.24.dev

Error message:
Algorithm started at: 2024-12-12T17:28:39
Algorithm 'Meteorological Data: Download data (ERA5)' starting…
Input parameters:
{ 'CRS' : QgsCoordinateReferenceSystem('EPSG:4326'), 'DATEINIEND' : '2019-12-31T00:00:00', 'DATEINISTART' : '2019-01-01T00:00:00', 'DIAG_HEIGHT' : 2, 'INPUT_POINT' : '1.5,43.5 [EPSG:4326]', 'OUTPUT_DIR' : 'C:\\Users\\scully\\Dropbox\\eXchange\\QGISprojects\\Toulouse\\_ERA5data\\test2' }

SuPy version: 2024.5.24.dev
INPUT PARAMETERS:
lat = 1.5
lon = 43.5
Start = 2019-01-01T00:00:00
End = 2019-12-31T00:00:00
Diagnostic height = 2.0
Output folder = C:\Users\scully\Dropbox\eXchange\QGISprojects\Toulouse\_ERA5data\test2
Traceback (most recent call last):
File "C:\Users/scully/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\preprocessor\copernicusera5_algorithm.py", line 182, in processAlgorithm
sp.util.gen_forcing_era5(lat, lon, startDate, endDate, hgt_agl_diag=diagHeight, dir_save=Path(outputDir))
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\supy\util\_era5.py", line 733, in gen_forcing_era5
list_fn_sfc, list_fn_ml = load_filelist_era5(
^^^^^^^^^^^^^^^^^^^
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\supy\util\_era5.py", line 627, in load_filelist_era5
download_era5(
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\supy\util\_era5.py", line 523, in download_era5
download_cds(path_dir_save / fn_sfc, dict_req)
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\supy\util\_era5.py", line 455, in download_cds
c.retrieve(**dict_req)
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\datapi\legacy_api_client.py", line 179, in retrieve
return submitted if target is None else submitted.download(target)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\datapi\processing.py", line 659, in download
robust_download(url, target)
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\multiurl\http.py", line 479, in wrapped
r = call(main_url, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\datapi\processing.py", line 625, in _download
multiurl.download(
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\multiurl\downloader.py", line 111, in download
return Downloader(url, **kwargs).download(target)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\multiurl\base.py", line 123, in download
with self.progress_bar(
^^^^^^^^^^^^^^^^^^
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\multiurl\base.py", line 49, in progress_bar
return tqdm(
^^^^^
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\tqdm\std.py", line 1098, in __init__
self.refresh(lock_args=self.lock_args)
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\tqdm\std.py", line 1347, in refresh
self.display()
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\tqdm\std.py", line 1495, in display
self.sp(self.__str__() if msg is None else msg)
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\tqdm\std.py", line 459, in print_status
fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\tqdm\std.py", line 452, in fp_write
fp.write(str(s))
^^^^^^^^
File "C:\Users\scully\AppData\Roaming\Python\Python312\site-packages\tqdm\utils.py", line 140, in __getattr__
return getattr(self._wrapped, name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'

Execution failed after 20.78 seconds

Loading resulting layers
Algorithm 'Meteorological Data: Download data (ERA5)' finished

**Comment by biglimp** [comment]
Did you try to download outside of QGIS/UMEP and if so, did it work?
As stated in the manual, the cdsapi can be very slow.

**Comment by CsillaVG** [comment]
No problem downloading ERA5 data outside of QGIS/UMEP . In this configuration, a single request sent to and received by Copernicus. The process dies during the next, downloading step.

**Comment by CsillaVG** [comment]
Update. Running UMEP developmental resolved the above error. 
Unfortunately, the upstream issue with nc file formatting is still there.

**Comment by sunt05** [comment]
Unfortunately, we cannot assist with the upstream issue.

@biglimp We should perhaps issue a warning from the UMEP side that this plugin may not work properly due to the upstream issue. We might also consider deprecating it and suggest users explore other approaches for ERA5 data.

**Comment by biglimp** [comment]
Sure. Any suggestions onwht to write in such a warning message?

**Comment by sunt05** [comment]
> Any suggestions onwht to write in such a warning message?


How about this: 

“Warning: This plugin is affected by an upstream issue and will be deprecated. Avoid using it in production and explore alternative methods for ERA5 data.”

**Comment by biglimp** [comment]
Could we more specific on the upstream issue and also be more specific on the alternatives? I dont think many user understand upstream issue...

**Comment by sunt05** [comment]
The upstream issue is detailed here: https://github.com/UMEP-dev/UMEP/issues/685#issuecomment-2547039370

For an alternative method for ERA5, perhaps direct them to the official CDS site?

**Comment by biglimp** [comment]
If there is just an issue with nc-files being in zip-format, cant we add an unzip functionality to the supy code? 

I do not think it is very helpful to direct them CDS site as they still need to convert to nc-files to UMEP-format.

I think it is crucial that we help users the best way we can to prepare met-forcing data as this is could be a stopper for many first time users. We can talk about this next year...
